### ISSUE TITLE
Onclick Listener of FCM is not working on foreground mode : ANDROID 12

### ISSUE THREAD

**Issue by Theamansinghrajput** [dpa99c/cordova-plugin-firebasex#764] opened 2022-09-24 08:20 UTC
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by ollm** [comment] 2022-09-26 07:17
Maybe related to this #763 
Try this solution #765

**Comment by Theamansinghrajput** [comment] 2022-09-26 17:37
Now notification is visible on foreground but click is still not working app is crashing. Check the attachment 

https://user-images.githubusercontent.com/109267226/192343077-846a576c-e212-46a7-ac3b-348ea8d2a95f.mp4

**Comment by Theamansinghrajput** [comment] 2022-09-26 17:50
@ollm Now foreground alert is visible but click is still crashing the app. Check the attachment...

https://user-images.githubusercontent.com/109267226/192345888-1e9a0cf3-c9c0-493b-b473-52660a53a9c7.mp4

**Comment by ollm** [comment] 2022-09-27 10:47
@Theamansinghrajput Can you put the stack trace from Firebase Crashlytics or Android Studio Logcat? to see what produces the crash.

**Comment by ollm** [comment] 2022-09-27 16:26
Are you using the latest version of the plugin? this bug is the same as this #746 and it is fixed in the latest versions `14.2.0+`

**Comment by Theamansinghrajput** [comment] 2022-09-28 16:19
Not fixed yet i am using updated plugin... @ollm

**Comment by Theamansinghrajput** [comment] 2022-09-28 16:23
issue is still on foreground click. Background notification click is working fine but foreground notification click is crashing the application. @ollm @dpa99c

**Comment by ollm** [comment] 2022-09-29 16:12
Don't you have in Firebase others errors?

**Comment by ollm** [comment] 2022-10-05 10:02
You should talk to @dpa99c, I don't have enough knowledge about the plugin to be able to help you find the cause of the error, sorry.

**Comment by dpa99c** [comment] 2022-11-23 14:35
Should be fixed in `cordova-plugin-firebasex@15.0.0` which has just been released to npm

**Closed by dpa99c** 2022-11-23 14:35 UTC
Labels: runtime issue, android, Cloud Messaging
