### ISSUE TITLE
Not receiving property "tap" IOS

### ISSUE THREAD

**Issue by mateusduraes** [dpa99c/cordova-plugin-firebasex#61] opened 2019-07-26 18:34 UTC
Hi

This plugins seems to work fine. I'm testing my app IOS app in development mode.
I receive the notifications that i send from firebase console, but, when the app is closed and I tap the notification, the app opens but there is no information about the property `tap.`

Those are the only informations that I receive

```
aps: {alert: {title: "Be Tester", body: "Hello, how are you?"}}
foo: "bar"
gcm.message_id: "1564165799854825"
gcm.n.e: "1"
google.c.a.c_id: "7897239349476441347"
google.c.a.e: "1"
google.c.a.ts: "1564165799"
google.c.a.udt: "0"
messageType: "notification"
```

Can someone give me help?

**Comment by jakupi1** [comment] 2019-07-27 09:47
Same problem here

**Comment by dpa99c** [comment] 2019-07-27 18:47
I'm not able to reproduce this issue when testing using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) with the latest version (`6.0.2`) of this plugin.

[This screen capture](http://ge.tt/63S4iHx2) shows the [`ios_notification_custom_sound_and_badge.json`](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/ios_notification_custom_sound_and_badge.json) message being sent via the FCM v1 API using the client in the test project.

[This screen capture](http://ge.tt/4fgBiHx2) shows a notification message sent from the Firebase Console with the `notification_foreground: true` key in the data payload.

In both, there a 3 scenarios illustrated:

- 1: Notification message arrives while app is running in foreground and notification is tapped
- 2: Notification message arrives while app is running in background and notification is tapped
- 2: Notification message arrives while app is not running (has been task killed) and notification is tapped

As you'll see, in all situations the `tap` key is present with the expected value.

I would urge you to repeat the same tests as above by building and running the example project and report your results here.

**Comment by mateusduraes** [comment] 2019-07-29 14:16
Hi @dpa99c, thank you so much for the feedback so quickly.
It worked like a charm in the test project but i still have problems in my project.

**Comment by jakupi1** [comment] 2019-07-29 14:20
@mateusduraes use this body https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/notification.json, i had the same problem for iOS but using this body fixed and now it works

**Comment by dpa99c** [comment] 2019-07-29 14:23
@mateusduraes thanks for the update. will close for now.

**Comment by mateusduraes** [comment] 2019-07-29 18:46
Hi, after some debug i realize that i still not receiving the property `tap`. 
I'm using the Firebase Admin SDK in cloud functions to send my notification. My payload is like the following:

```json
{
    "topic": "1289_1352",
    "notification": {
        "body": "Be Member: Hello guys",
        "title": "Be Member"
    },
    "android": {
        "priority": "normal",
        "ttl": 3600,
        "notification": {
            "sound": "default",
            "color": "#0099ff",
            "icon": "fcm_push_icon"
        }
    },
    "apns": {
        "payload": {
            "aps": {
                "badge": 1,
                "sound": "default"
            }
        }
    },
    "data": {
        "ownerName": "Be Member",
        "ownerPicture": "https://be-api-production.s3.eu-central-1.amazonaws.com/production/upload/user_image_upload/99557/upload",
        "chatMessage": "Hello guys",
        "type": "new_message",
        "channelId": "1289_1352",
        "messageId": "M6f4bR9x7m0VCmsK61pL"
    }
}
```

In my application I received the following in "onMessageReceived" callback

```swift
aps: {alert: {title: "Be Member", body: "Be Member: Hello guys"}, badge: 1, sound: "default"}
channelId: "1289_1352"
chatMessage: "Hello guys"
gcm.message_id: "1564425263106447"
google.c.a.e: "1"
messageId: "M6f4bR9x7m0VCmsK61pL"
messageType: "notification"
ownerName: "Be Member"
ownerPicture: "https://be-api-production.s3.eu-central-1.amazonaws.com/production/upload/user_image_upload/99557/upload"
type: "new_message"
```

When I send the push-notification using a script in your test project, with the following command,

```bash
npm run-script send -- --message=notification.json --token="cyue3zCM58o:APA91bGeOiciQhMlcAie--Np35CtYiTtZqtpxKUQyT97ahROTeIK5Q8aBjcCyg_lY2wHA5vyRc1zJumUGIWsp4-aCqM2d7sdI4wd6BrxRO1SbfeMTa7iSAXeTPJiSf1596xE3SqKGNuZ"
```

My app crashes and i see the following log in my xcode

```swift
2019-07-29 15:44:11.947966-0300 My Runcard[2820:858944] didReceiveRemoteNotification: {
    aps =     {
        alert =         {
            body = "Notification with default settings";
            title = "Default Notification";
        };
        badge = 1;
        sound = default;
    };
    "gcm.message_id" = 1564425851513033;
    "google.c.a.e" = 1;
    "key_1" = "Data for key one";
    messageType = notification;
    "notification_foreground" = true;
}

2019-07-29 15:44:11.953574-0300 My Runcard[2820:859023] -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xd900dc6a1b315eeb
2019-07-29 15:44:11.954552-0300 My Runcard[2820:859023] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xd900dc6a1b315eeb'
*** First throw call stack:
(0x1ac65d27c 0x1ab8379f8 0x1ac579ab8 0x1ac662ac4 0x1ac66475c 0x102299634 0x10312b6f0 0x10312cc74 0x103134bf4 0x1031358ec 0x10313f77c 0x1ac27d114 0x1ac27fcd4)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Am i doing something wrong? I'm sorry

**Comment by jakupi1** [comment] 2019-07-29 18:51
What are you using as backend? Either add tap manually and modify it.

**Comment by mateusduraes** [comment] 2019-07-29 18:54
Hi @jakupi1 , I'm using NodeJS (Firebase Cloudfunctions), i can easily add the property ```tap```with a default value that I don't know yet, but the plugin should change it's value, this is what you mean?

**Comment by mateusduraes** [comment] 2019-07-29 19:46
I've tried to set a default value to property `tap`, but the plugin doesn't change its value, so, it doesn't solve my problem.

I'll be waiting for @dpa99c suggestions, so I can investigate more.

**Comment by mateusduraes** [comment] 2019-07-29 21:13
@dpa99c It only works when I put the following instruction on line 132 of **AppDelegate+FirebasePlugin.m**:

```objectivec
[mutableUserInfo setValue:self.applicationInBackground forKey:@"tap"];
```

So, now, I'm able to receive the property tap as a boolean.

This make any sense?
I can create a PR adding the correct value ("background" | "foreground") if you want.

**Comment by dpa99c** [comment] 2019-07-30 05:31
@mateusduraes just to confirm - in your scenario, is the call to `onMessageReceived()` triggered by:
- a notification message arriving while app is in the foreground?
- tapping a notification while the app is in the foreground?
- tapping a notification while the app is in the background (but running)?
- tapping a notification while the app is not running?

**Comment by freddysu** [comment] 2019-07-30 07:41
I got the same issue in my project but not in the example project as well.

On Android it works perfectly in both foreground and background.

On iOS, when a notification message arriving while app is in the foreground, it crashes.
When the app is in the background or not running, when I tap the notification it won't crash but I realised that no ``tap`` attribute in the ``onMessageReceived`` callback either.

**Comment by freddysu** [comment] 2019-07-30 07:57
I got the similar issue in my project but not in the example project as well.
On Android it works perfectly in both foreground, background and not running.

On iOS, when I set "notification_foreground" to "true",
 - A notification message arriving while app is in the foreground, it crashes.
 - A notification message arriving while app is in the background, I tapped the notification and it crashes too.
 - When the app is not running, I tapped the notification it won't crash and worked perfectly.

So the next thing I tried is to remove the "notification_foreground" attribute.

On iOS, when I send a notification without the "notification_foreground" attribute, my app won't crash when a notification arriving either in foreground, background or not running.
However, I realised that no "tap" attribute in ``onMessageReceived`` callback anymore either.

Thanks for the help!

**Comment by dpa99c** [comment] 2019-07-30 08:04
Reopening as there's obviously some underlying issues here.

One thing I will do is add top-level exception handling for iOS (like I've done for Android) to prevent app crashes.

@mateusduraes With regard to the cause of your crash, I suspect the problem is the sound attribute. In your crashlog I see the sound value is shown as `sound = default;` i.e. not `sound = "default";` and the exception message is `[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance` so I think that's being raised on [this line](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/AppDelegate%2BFirebasePlugin.m#L215) because it's trying to compare `sound` as a string but it looks like it's not actually an `NSString*`. I'll need to investigate why this is.

@freddysu with regard to the `tap` attribute, it should only be set if the notification is actually tapped - it shouldn't be set when `onMessageReceived()` is called in response to a notification message actually being received by the app directly from FCM (i.e. notification not tapped by user).

**Comment by freddysu** [comment] 2019-07-30 08:12
Thanks for the quick reply. Sorry for the incorrect description above. I've edited my comment:)

**Comment by mateusduraes** [comment] 2019-07-30 13:30
> @mateusduraes just to confirm - in your scenario, is the call to `onMessageReceived()` triggered by:
> 
> * a notification message arriving while app is in the foreground? **Yes, i receive it**
> * tapping a notification while the app is in the foreground? I'm not using the property `notification_foreground`, but for me, it doesn't work.
> * tapping a notification while the app is in the background (but running)? **Yes, i receive it**
> * tapping a notification while the app is not running? **Yes, i receive it**

**Comment by shinwenli** [comment] 2019-07-31 01:08
Although it may be another problem, my ios terminal could not receive system notification at foreground time. ("Notification_foreground" = true)
It was caused by calling "FirebasePlugin.grantPermission".
If you did not call "FirebasePlugin.grantPermission" (after getting the token once and restarting it), you could display the system notification.

The version is "cordova-plugin-firebasex 6.0.2".

**Comment by freddysu** [comment] 2019-07-31 05:14
@shinwenli You are right! Thanks for your feedback.

If I removed the "FirebasePlugin.grantPermission()", it works perfect on iOS.

Now I just call "getPermission" the first time after the app is installed, which means only at the first time when the user opens the app, grant the permission and then if there is a notification arrives will crash the app.

After the user restarts the app, it works perfectly in "foreground", "background" and "not running" even with the "notification_foreground" attribute on iOS.

**Comment by syagawa** [comment] 2019-07-31 07:04
I had the same problem.
But, solved by "not calling grantPermission".

In my app, call hasPermission then call grantPermission.
I was expecting Object to be an argument of the hasPermission callback, but it was actually boolean.
hasPermission becomes false, and grantPermission has been called.

This problem occurred because I changed the plugin of the app from "cordova-plugin-firebase" to "cordova-plugin-firebasex".

thank you @shinwenli, @dpa99c

**Comment by jpduckwo** [comment] 2019-08-01 05:32
Definitely solved for me by making sure grantPermission was not called unless hasPermission returns false... all worked after that! Thanks

**Comment by Lucab95** [comment] 2019-08-05 16:35
> @shinwenli You are right! Thanks for your feedback.
> 
> If I removed the "FirebasePlugin.grantPermission()", it works perfect on iOS.
> 
> Now I just call "getPermission" the first time after the app is installed, which means only at the first time when the user opens the app, grant the permission and then if there is a notification arrives will crash the app.
> 
> After the user restarts the app, it works perfectly in "foreground", "background" and "not running" even with the "notification_foreground" attribute on iOS.

I have the same problem(notifications work only after restarting the app), has the last commit solved the issue?

**Comment by yoldar** [comment] 2019-08-06 11:09
> Hi @dpa99c, thank you so much for the feedback so quickly.
> It worked like a charm in the test project but i still have problems in my project.
> 
> I will make some investigations and let you know. I believe you can close the issue for now.

Same problem with my project :(

**Comment by dpa99c** [comment] 2019-08-06 19:26
I've just published v6.0.3 which should address the multiple problems captured in this issue.
Please regression test and let me know if there are still any issues, but I will close this for now as I believe they have all been addressed.

**Closed by dpa99c** 2019-08-06 19:26 UTC
Labels: ios, runtime issue

**Comment by ghidoz** [comment] 2019-08-16 18:29
Hi, I'm using v6.0.6 and still there is a problem with the tap property on iOS.

Steps to reproduce:
- Install the app on iPhone the first time
- Call grantPermission for asking for perms
- Put the app in background
- Send a notification
- Tap on it
- View the response in console: no tap property

However, if I close the app completely and open it again, since I don't call grantPermission again, I recevie the tap property when tapping on the system notification.

So the problem is still present, when calling grantPermission.

**Comment by yoldar** [comment] 2019-08-24 18:12
> Hi, I'm using v6.0.6 and still there is a problem with the tap property on iOS.
> 
> Steps to reproduce:
> 
> * Install the app on iPhone the first time
> * Call grantPermission for asking for perms
> * Put the app in background
> * Send a notification
> * Tap on it
> * View the response in console: no tap property
> 
> However, if I close the app completely and open it again, since I don't call grantPermission again, I recevie the tap property when tapping on the system notification.
> 
> So the problem is still present, when calling grantPermission.

Same problem

**Comment by Yuripetusko** [comment] 2019-08-29 23:04
Same here, I get tap property only if app is completely closed when clicking on notification

**Comment by shinwenli** [comment] 2019-09-19 08:17
I was able to solve this problem with Version 6.1.0.

Thank you @dpa99c.
