### ISSUE TITLE
Android Default Notification Icon : Using config-file don't generate correctly AndroidManifest.xml

### ISSUE THREAD

**Issue by nvelin-zaggo** [dpa99c/cordova-plugin-firebasex#85] opened 2019-08-12 13:31 UTC
I try to set up a custom default icon for my app.

When adding this block in the platform android of the config.xml,
```
<config-file target="AndroidManifest.xml" parent="application">
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
    </config-file>
```
The generate AndroidManifest.xml will be very different from the last one generated (without these new lines)

For example, i lost
```
<service android:enabled="true" android:exported="false" android:name="com.google.android.gms.measurement.AppMeasurementService" />
<service android:name="org.apache.cordova.firebase.FirebasePluginMessagingService">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>
<receiver android:name="org.apache.cordova.firebase.OnNotificationOpenReceiver" />
<meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/accent" />
<meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id" />
```

I can add manually 
```
<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
```
in the AndroidManifest.xml and it's works

Anybody have the same behavior ?

**Comment by dpa99c** [comment] 2019-08-13 07:01
I can reproduce this with `cordova@9` in an isolated test project, so I've raised it as an issue against `cordova-android`: https://github.com/apache/cordova-android/issues/809

In the meantime, I've worked around this in the [test project](https://github.com/dpa99c/cordova-plugin-firebasex-test) by adding [cordova-custom-config](https://github.com/dpa99c/cordova-custom-config) to the project as [using its `<custom-config-file>` blocks in `config.xml`](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/config.xml#L40):

    <custom-config-file parent="./application" target="AndroidManifest.xml">
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
    </custom-config-file>

Will close this issue however as this is caused by a bug in Cordova not in this plugin.

**Closed by dpa99c** 2019-08-13 07:01 UTC

**Comment by benskarunya** [comment] 2019-08-19 04:47
Hi,
I am using cordova@9.0.0 and Android@8.0.0, i am facing issue with the android notification icon getting gray color. And i tried adding meta-data as well, still not receiving notification icon
<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />. Please advise

**Comment by VincentPuget** [comment] 2019-10-02 15:05
Hi,

I solved this problem using this 
```
<config-file parent="/manifest/application" target="AndroidManifest.xml" xmlns:android="http://schemas.android.com/apk/res/android">
    <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
</config-file>
```

Ionic CLI: 5.4.2
Cordova CLI: 9.0.0
Cordova Platforms : android 8.1.0, ios 5.0.1

**Comment by ivanosire** [comment] 2019-10-07 11:14
I confirm that using "/manifest/application" instead of "application" in the parent tag resolves the cordova bug and overwrite problems.

I have send [this pull request](https://github.com/dpa99c/cordova-plugin-firebasex/pull/174) to update documentation.

**Comment by ivanosire** [comment] 2019-10-07 14:22
I confirm that config-file parent tag must contain "**/manifest/application**" value to avoid android Manifest overwrite error from cordova. So use of cordova-custom-config plugin is not necessary.

@dpa99c please update example code [pull/174](https://github.com/dpa99c/cordova-plugin-firebasex/pull/174)

Thanks
