### ISSUE TITLE
Xcode attempts to sign the pods and the build fails

### ISSUE THREAD

**Issue by charpour** [dpa99c/cordova-plugin-firebasex#127] opened 2019-09-03 11:34 UTC
Recently switched to the cocoapods approach of consuming dependencies (firebasex) but unfortunately the build has started failing:

```
2019-09-03 02:47:38   : User defaults from command line:
2019-09-03 02:47:38   :     IDEArchivePathOverride = ...
2019-09-03 02:47:38   :     IDEBuildOperationMaxNumberOfConcurrentCompileTasks = 1
2019-09-03 02:47:38   :     UseModernBuildSystem = NO
2019-09-03 02:47:38   : 
2019-09-03 02:47:38   : Build settings from command line:
2019-09-03 02:47:38   :     CODE_SIGN_IDENTITY =...
2019-09-03 02:47:38   :     CODE_SIGN_STYLE = Manual
2019-09-03 02:47:38   :     PROVISIONING_PROFILE = ...
2019-09-03 02:47:38   :     PROVISIONING_PROFILE_SPECIFIER = ...
2019-09-03 02:47:38   :     SDKROOT = iphoneos12.1
2019-09-03 02:47:38   : 
2019-09-03 02:47:39   : Prepare build
2019-09-03 02:47:39   : note: Using legacy build system
2019-09-03 02:47:39   : 
2019-09-03 02:47:39   : Build Preparation
2019-09-03 02:47:39   : Build task concurrency set to 1 via user default IDEBuildOperationMaxNumberOfConcurrentCompileTasks
2019-09-03 02:47:39   : 
2019-09-03 02:47:39   : === BUILD TARGET GoogleUtilities OF PROJECT Pods WITH CONFIGURATION Release ===
2019-09-03 02:47:39   : 
2019-09-03 02:47:39   : Check dependencies
2019-09-03 02:47:40   : Code Signing Error: GoogleUtilities does not support provisioning profiles. GoogleUtilities does not support provisioning profiles, but provisioning profile 3065ee94-f44c-4868-ae0e-e1016bef0c7e has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.
2019-09-03 02:47:40   : 
2019-09-03 02:47:40   : === BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Release ===
2019-09-03 02:47:40   : Check dependencies
```

It seems that xCode is trying to sign the pods when such operation is not supported.

I've tried several approaches to resolve the issue, but nothing has worked so far. Usually suggestions to fix this include adding post_install step that disables signing for all of the pods.

Any ideas/suggestions would be more than welcome

**Comment by dpa99c** [comment] 2019-09-03 15:38
From the error message, it looks like a provisioning profile has been manually specified for GoogleUtilities in Xcode - this plugin does not alter the signing configuration.
Open the project in Xcode, select the Pods project, select the GoogleUtilities target and ensure no provisioning profile has been selected.

Please try building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to validate your development environment and rule out other causes in your project.

**Comment by charpour** [comment] 2019-09-03 16:11
I'd love to be able to do that but I'm using a build farm node and I have no direct access to it, I can only issue shell commands. Is there some way I can do that via the command line that you're aware of?

**Comment by dpa99c** [comment] 2019-09-03 16:14
Since you're using a remote build environment, I'm afraid it will be up to you to diagnose the Pods issue. Suffice to say that if you build the example project locally you will find that it builds OK and therefore the problem is not caused by this plugin. For that reason, I'm closing this issue as there's nothing that can be done from the perspective of the plugin code.

**Closed by dpa99c** 2019-09-03 16:14 UTC
Labels: awaiting response, build issue, ios, support

**Comment by charpour** [comment] 2019-09-03 16:18
would cocoapods be the only supported way to consume dependencies going forward?

**Comment by dpa99c** [comment] 2019-09-03 16:20
yes - it's the industry-standard way of consuming 3rd-party dependencies when building iOS apps
