### ISSUE TITLE
iOS - not getting value for (<any>window).FirebasePlugin, currently value is {}

### ISSUE THREAD

**Issue by danielvalenciaz** [dpa99c/cordova-plugin-firebasex#442] opened 2020-07-01 19:57 UTC
Current behavior:

First of all, Thanks a lot for this awesome plugin, I am using this plugin witn Ionic 3.
I am on iPhone XS Max/iOS 13.4 and I've tried everything since last 2 days on this issue

Still no avail. To summarize:

I've Checked on multiple plugin versions i.e. 7.0.x till 9.0.1
I've checked my bundle identifier matches the one in provisioning profile/development portal
I've created a new development push APNS certificate
I've created a new development certificate
I've created a new provisioning profile for that development certificate
I've downloaded both the certificate and provisioning profile, and obviously, double clicked them to install
I've verified that everything is right on Developer Portal: all certificates and provisioning profiles valid, push enabled and configured with my new APNS certificate
I've uploaded my new APNS certificate to firebase console
I've also tried with .p8 key on firebase console
I've made sure that I'm using the correct certificate/provisioning profile pair at Xcode to codesign
I've checked Notifications settings in case my app is not allowed to receive pushes, it's not there
I've tried setting date manually to tomorrow and tried re-installing the app
I've deleted the app from my device
I've deleted any related provisioning profiles from my device
I've restarted my device multiple times
I've switched my device network to cellular from wifi & vice versa multiple times

Please Please any help would be highly appreciated

Expected behavior:
I should be able to receive push notifications when app is closed or in background

Steps to reproduce:

Screenshots

Environment information

Ionic Info
Ionic:

   Ionic CLI          : 6.10.1 (/Users/dvalencia/.nvm/versions/node/v10.16.0/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 6.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 20 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.3.0
   native-run (update available: 1.0.0)   : 0.2.6

System:

   Android SDK Tools : 26.1.1 (/Users/dvalencia/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.0 (/Users/dvalencia/.nvm/versions/node/v10.16.0/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c

Cordova CLI version
9.0.0 (cordova-lib@9.0.1)
Cordova platform version
ios 6.1.0
Plugins & versions installed in project (including this plugin)
cordova-plugin-advanced-http 2.5.1 "Advanced HTTP plugin"
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-geolocation 3.1.0 "CDVBackgroundGeolocation"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-document-viewer 0.9.13 "SitewaertsDocumentViewer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 10.1.0-cli "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 5.0.2 "Diagnostic"

Dev machine OS and version, e.g.
OSX
ProductName: Mac OS X
ProductVersion: 10.15.5
Runtime issue

Device details
iPhone XS Max
OS details
iOS 13.4
iOS build issue:
Node JS version
v10.16.0
XCode version
Version 11.5 (11E608c)

**Comment by MLuan** [comment] 2020-07-01 20:03
I'm have this same issue, for some reason i don't receive notifications when app is in background or is closed.  But in console i can see the notification when i open the app again. 
I already tried all the same things that list here but no success. 
I'm use too ionic 3. 
With the older plugin, the native one i can receive notifications, but after migration i can't get T_T

**Comment by brassier** [comment] 2020-07-01 20:21
I **_AM_** able to get background (app open or closed) and foreground notifications to work on iOS, with Ionic 3.  I am currently using:

- version `7.0.2` of the firebasex plugin
- cordova-ios `5.1.1`

We have seen notifications work just fine on newer iPhones (iPhone 11) as well as older iPads that don't support iOS 13. 

You may benefit from:

1. Starting with an empty project with no other plugins, and seeing if that will work.  
1. Checking other closed issues that are similar (e.g. [this one](https://github.com/dpa99c/cordova-plugin-firebasex/issues/187)).
1. As @dpa99c often wisely suggests:
> Try building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to eliminate possible problems in your codebase

**Comment by dpa99c** [comment] 2020-07-01 21:28
As @brassier suggests, please use the example project to regression test as it's a known codebase. This plugin is in wide production usage in numerous apps (including my own) so it's highly likely that the issue is specific to your configuration vs a universal problem affecting all users of this plugin.
That said, if you are able to provide a reproducible test case of the issue in the context of the example project, I will be happy to investigate further. 
However until such time as this evidence is provided I am closing this on the assumptive basis of a user support issue.

**Closed by dpa99c** 2020-07-01 21:28 UTC

**Comment by danielvalenciaz** [comment] 2020-07-02 00:24
Thanks guys, all your solutions are valid, push notification come alive again. Great support !!!

**Comment by MLuan** [comment] 2020-07-03 17:48
> Thanks guys, all your solutions are valid, push notification come alive again. Great support !!!

@danielvalenciaz  can you help me? 
I always keep receiving "FirebasePlugin[native]: Enter foreground: FCM direct channel = true" when app is in foreground and 
"FirebasePlugin[native]: Enter foreground: FCM direct channel = false" when is in background. I follow the docs and dosen't work for me. 
When app is in background the notification dosent show in console, only when i open app again. You did something diferent? 
Thank you

**Comment by danielvalenciaz** [comment] 2020-07-06 23:43
Hi @MLuan I have reviewed it and I have the same problem, push notifications are working only in background, when I tested in foreground, they are not working. Maybe @dpa99c could help us with that issue!

**Comment by dpa99c** [comment] 2020-07-07 07:56
@danielvalenciaz Foreground notifications are not something supported by Firebase so this plugin adds them as an extra layer of functionality. 
Therefore [as documented](https://github.com/dpa99c/cordova-plugin-firebasex#foreground-notifications), you need to send `"notification_foreground": "true"` in the `data` section of the notification message to trigger this functionality.
You can validate this using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) which has a [built-in FCM v1 API messaging client](https://github.com/dpa99c/cordova-plugin-firebasex-test#messaging-client) to send [predefined test messages](https://github.com/dpa99c/cordova-plugin-firebasex-test/tree/master/messages).

**Comment by MLuan** [comment] 2020-07-14 16:10
@danielvalenciaz  hi again :) 
So, for the last weeks i have tried to make push notification work on IOS ( android works fine ). 
I'm using ionic 3, so i have to use (<any>window).FirebasePlugin.... 
I can get the fcm token and received message from firebase console, but the notification dosen't show up. So i put a console.log on onMessageReceived() and the notification comes to app, as describe in the print screen bellow
![image](https://user-images.githubusercontent.com/22017044/87448582-08355500-c5ca-11ea-8220-36c515b38cdd.png)
and i can only see this when app is open, if i send a notification in firebase console with the app in backgroun or closed, nothing happens on console, only when app is in foreground.

So i figure out that the firebase configuration, certificates, profiles and keys are working. But why the popup dosent show up? 

I already tried with the Firebase test project but nothing happens too, same behavior.
So pls, can you help me? i realy don't know what else i can do.

Thanks :)
