### ISSUE TITLE
Demo Application APNS Token: null

### ISSUE THREAD

**Issue by sprengerst** [dpa99c/cordova-plugin-firebasex#278] opened 2020-01-19 13:58 UTC
Hello,

we setup everything as described in the Medium Link for setting up APNS. Also we used the firebasex Demo application. A click on "Get APNS token" leaves us with "null" as a result. A "Get FCM ID" returns a valid device token. We don't receive APNS background messages, because of the missing APNS token.

It doesn't matter if we use a real device or simulator, the APNS field stays null. 

We tried manual setting a provisioning profile and importing p12 certificates development/production to Firebase. Our next try was to go with the newer version, with a p8 certificate and automatic signing of the app, also there we had no luck.

Do you have any ideas what could be wrong in our setup, we tried literally anything to get this to work. We followed all instructions exactly, even multiple times. Could you maybe detail the signing/provisioning part a little bit, we think that there could be a missing piece, which leads us to the error?

We use your demo application 1:1, changed from your bundle id to ours, and replaced both Firebase configuration files from our Firebase console setup. 

Best Wishes,
Stefan

**Comment by sprengerst** [comment] 2020-01-19 14:36
Also the permission is granted, seen in the logs. What I find a bit wondering is, that "registerForRemoteNotifications" is shown two times:


2020-01-19 15:32:30.714887+0100 FirebaseTest[1344:259729] requestAuthorizationWithOptions: granted=YES
2020-01-19 15:32:30.715088+0100 FirebaseTest[1344:259729] registerForRemoteNotifications
2020-01-19 15:32:30.741275+0100 FirebaseTest[1344:259729] registerForRemoteNotifications
2020-01-19 15:32:30.741634+0100 FirebaseTest[1344:259729] _hasPermission: YES
2020-01-19 15:32:30.752758+0100 FirebaseTest[1344:259673] Remote notifications permission granted
2020-01-19 15:32:30.769068+0100 FirebaseTest[1344:259673] Got FCM token: dq******uIHj9M
2020-01-19 15:32:31.075347+0100 FirebaseTest[1344:259673] FCM direct channel = true

**Comment by sprengerst** [comment] 2020-01-27 19:25
We finally fixed it!! 
There was no problem with APNS configuration. 

**If you test your code with an iPhone, which has never had a sim card inserted, then you don't get an APNS token.**

After putting in a sim card we got an APNS token, even if we remove it later. Thank you apple 👎

**Comment by dpa99c** [comment] 2020-01-27 21:22
Thanks for posting the cause of the issue. I had tried to repro your issue with no success but I guess because the two iPhones I use for testing both have SIM cards in.

I'll close this now as you've resolved the issue.

**Closed by dpa99c** 2020-01-27 21:22 UTC
