### ISSUE TITLE
iOS: Background Notification is Not Presenting Alert

### ISSUE THREAD

**Issue by kartiksolanki** [dpa99c/cordova-plugin-firebasex#400] opened 2020-05-19 19:05 UTC
Hi,
I am using Ionic with this plugin. I am having issues with my iOS when the application is in background and killed/not running. My implementation is as follow:

```
this.fcm.onMessageReceived().subscribe(async (notification: any) => {
        console.log("Message type: " + notification.messageType);
        if(notification.messageType === "notification"){
          console.log("Notification message received");
          if (notification.tap === 'background') {
            //Received in Background
            console.log('Background Notification: ', JSON.stringify(notification));
            this.presentToastWithOptions(notification);
          } else { 
            // Received in foreground
            console.log('Foreground Notification: ', JSON.stringify(notification));
            this.presentToastWithOptions(notification);
          }
        }
        console.dir(notification);
      }, function(error) {
          console.error(error);
      });
```

There are 3 scenarios:

1. Notification in Foreground: This is working perfectly.
2. Notification in Background when App is not killed: This is also working perfectly.

3. Notification in Background when App is Killed(or not running in background ): In this scenario,
I am getting the system tray for the notification, and when I click on my notification, it opens the app as well but my notification alert is not being displayed.  Any idea what am I doing wrong? I am also sending "content-available":1 in my apns.payload.aps as per the documentation. Please help.

**Comment by dpa99c** [comment] 2020-05-19 21:36
I've regression tested using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) and the empirical result shows the plugin is correctly passing notification payload to the app on startup when it is launched by tapping a system notification after being task-killed - see [this screencapture](http://ge.tt/8jNCVY33).

The [`ios_notification_default_sound_and_badge`](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/ios_notification_default_sound_and_badge.json) test noification message sent was sent using the example project's built-in FCM v1 API client since this message also contains `"content-available": 1`.

From my perspective there is no issue with the plugin passing the message payload to the app after is has been killed in the background so I'm closing this issue.

I recommend you repeat the test using the example project and same test message via the built-in API client and confirm if you see the same results as in my screen capture.
If not, the issue could be your APNS setup in Firebase.

**Test environment information**
- Cordova CLI version 
    - `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `cordova-ios@5.0.1`
- Test project version: `cordova-plugin-firebasex-test@9.1.0`
- Plugins & versions installed in project (including this plugin)
```
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-customfcmreceiver 1.0.0 "Custom FCM Receiver"
cordova-plugin-dialogs 1.3.2-dev "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-firebasex 9.1.1 "Google Firebase Plugin"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```
- Dev machine OS and version, e.g.
    - OSX 10.15.2
        
_Runtime issue_
- Device details
    - iPhone 7
- OS details
    - iOS 13.3.1
	
_iOS build issue:_
- XCode Version 11.4 (11E146)

**Closed by dpa99c** 2020-05-19 21:36 UTC

**Comment by kartiksolanki** [comment] 2020-05-20 13:19
This is the payload I am sending:
```
const Message = {
        "notification": {
          "title": title,
          "body": content, 
          "sound": "default",
          "priority": "High"
        }, 
        "data": {
          "title": title,
          "body": content,
          "notification_foreground": "true"
        },
        "apns": {
          "payload": {
            "aps": {
              "sound": "default",
              "content-available": 1
            }
          }
        },
      'to': user.id
      }
```

Is there anything wrong in that? Also, I checked my Firebase and I have APN Auth Key setup. I do receive the notification when my app in background is killed. And it does open the app as well on tap, but it doesn't show the display alert inside the app. My background notification handler looks like this:

```
if (notification.tap === 'background') {
            //Received in Background
            console.log('Background Notification: ', JSON.stringify(notification));
            this.presentToastWithOptions(notification);
          }
```

Do you think there is some error in that code????

**Comment by dpa99c** [comment] 2020-05-20 13:34
does this line get called?

> console.log('Background Notification: ', JSON.stringify(notification));



if so then maybe there's an issue parsing the data you are sending to this line:
> this.presentToastWithOptions(notification);

**Comment by kartiksolanki** [comment] 2020-05-20 13:36
The problem is I am not able to log that when my app is killed in background. Any idea how can I view those logs when app is killed?

**Comment by dpa99c** [comment] 2020-05-20 13:41
> The problem is I am not able to log that when my app is killed in background. Any idea how can I view those logs when app is killed?

You could:
- Append the message to the page: 
`document.body.innerHTML += '<pre>'+JSON.stringify(notification)'+'</pre>'`
- Run via Xcode and view the console log
- View the device log via Xcode

**Comment by kartiksolanki** [comment] 2020-05-20 15:56
I cannot append that to my home page as the "notification" variable is not availabe.

**Comment by yaro08** [comment] 2020-06-10 11:41
same issue, in my case I have onMessageReceived() do navigate to other page and it not doing if I kill the app. Someone know how to fix it?
