### ISSUE TITLE
Build failed for IOS

### ISSUE THREAD

**Issue by hengvenchang** [dpa99c/cordova-plugin-firebasex#171] opened 2019-10-04 08:10 UTC
<img width="1439" alt="Screenshot 2019-10-04 at 3 09 18 PM" src="https://user-images.githubusercontent.com/17307495/66191608-f62c9a80-e6b8-11e9-8255-4744a54e4d81.png">
i'm able to build with this plugin for android, but for ios it gets this weird error

cordova 9
cordova ios 5
cordova android 8

**Comment by dpa99c** [comment] 2019-10-04 08:15
Code 65 is often caused by an issue with code signing - nothing to do with this plugin - please check you are able to build without the plugin present.
Also try building the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to validate your build environment.

**Comment by hengvenchang** [comment] 2019-10-04 08:39
i cloned your example project and the build seems to work fine on my env

**Comment by dpa99c** [comment] 2019-10-04 08:41
That validates both your build environment and this plugin therefore the issue must lie within your actual app project. Check the provisioning profile is correct - try building in Xcode.

Closing this though as this has proved it's not an issue caused by this plugin.

**Comment by hengvenchang** [comment] 2019-10-04 08:41
after i remove the plugin cordova-plugin-firebasex, my own project also able to build! 
here is an error show on xcode when add plugin to project:
<img width="271" alt="Screenshot 2019-10-04 at 3 31 29 PM" src="https://user-images.githubusercontent.com/17307495/66193701-5d4c4e00-e6bd-11e9-956f-a3afd21e692d.png">

it said missing headerfile firebase.h

**Closed by dpa99c** 2019-10-04 08:41 UTC
Labels: build issue, ios, support

**Comment by dpa99c** [comment] 2019-10-04 08:43
did you open `.xcproject` or `.xcworkspace`? you must open `.xcworkspace` because the Firebase SDK is delivered via Cocoapods...
Also make sure your Cocoapods environment is configured and up-to-date [as documented](https://github.com/dpa99c/cordova-plugin-firebasex#cocoapods)

**Comment by hengvenchang** [comment] 2019-10-04 10:07
Yes i open the project with .xcworkspace. (my xcode is 11.0)

**Comment by dpa99c** [comment] 2019-10-04 10:11
then it may be caused by a conflict with another plugin - I cannot be sure as I cannot see the source code of your project. 
However, you have confirmed that the example project builds fine which confirms for me that this plugin is working correctly in isolation.
I'm afraid I can't support you in diagnosing the exact issue with your own project as there are too many possible variables. This is after all free, open-source software so you will need to diagnose the issue within your own project.

**Comment by hengvenchang** [comment] 2019-10-05 11:50
after 12 hours of debugging! now found the issue! 
The Reason is becus i have "cordova-plugin-cocoapod-support" plugin added in my project, after remove it, i'm able to build now

**Comment by harveyelsisura** [comment] 2020-04-11 05:45
I'm having a same problem right now, It takes me a lot of day but no solution fixed my problem. Please i need some help. *FCMplugin.m firebase.h not found*
