### ISSUE TITLE
Notification custom sound not working 

### ISSUE THREAD

**Issue by renznamoc21** [dpa99c/cordova-plugin-firebasex#449] opened 2020-07-12 11:24 UTC
Current behavior:
Custom sound not working, notification sound always use the default ringtone instead of custom sound 

Expected behavior:
To play custom sound setup in notification create channel

Steps to reproduce:
send notification using FCM built-in client in example project

npm run-script send -- --message=android_notification_custom_channel.json --token="fAGB24U2TR-Im2dGdIIZoc:APA91bHRjdhtM-IDv5ddZZvzBPY2XgZstxkxVyr2O6Ivfu4QhKLvWmTbEeU9KTQW17Y2Va34ZxG-HWIqsWSGOLe-cVNaA7EHiIwWvMTRGBnOz-gNnB5J2bgkg55JVW9eeaUkqmmqSNEV"

Screenshots:
https://paste.pics/c422afdedced10709549b980c653afc2 
https://paste.pics/da35747e4b86d430952a9f5f1d5b9faf

Environment information

Cordova CLI version 
9.0.0 (cordova-lib@9.0.1)

Cordova platform version 
Installed platforms:
  android 8.1.0
  
Plugins & versions installed in project (including this plugin) 
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-customfcmreceiver 1.0.0 "Custom FCM Receiver"
cordova-plugin-dialogs 1.3.2-dev "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-firebasex 10.1.0 "Google Firebase Plugin"
cordova-plugin-whitelist 1.3.4 "Whitelist"

Dev machine OS and version, e.g. 
Microsoft windows 
Version 1903 (OS Build 18362.900)

Runtime issue
Device details 
Samsung A50s - Android 10
Samsung A6 - 	Android 9

Android build issue:

Node JS version 
v12.16.3

Gradle version
------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_171 (Oracle Corporation 25.171-b11)
OS:           Windows 10 10.0 amd64

Target Android SDK version 
No define in example project

**Comment by dpa99c** [comment] 2020-07-13 10:59
I'm unable to reproduce this issue - please see this [screencapture video](http://ge.tt/7TmxxX53) using the example project app on a Google Pixel 2XL running Android 10.

The first message sent is [`topic_notification.json`](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/topic_notification.json) which [targets channel `fcm_default_channel`](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/topic_notification.json#L13) which is configured for the default notification sound.

The second message sent is [`topic_notification_custom_sound.json`](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/topic_notification_custom_sound.json) which  [targets channel `my_channel_id`](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/topic_notification_custom_sound.json#L13) which [is configured](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/www/js/index.js#L156) for [`blackberry.mp3`](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/res/android/raw/blackberry.mp3). 
You can see the [`sound` key in this message](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/topic_notification_custom_sound.json#L14) is set for [`msn.mp3`](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/res/android/raw/msn.mp3) to demonstrate that it is the channel ID which matters.

From the audio of the screencapture video, you can clearly hear that the custom notification sound - `blackberry.mp3` - is played for the second notification.

It may be that does Android OEMs (e.g. Samsung) don't allow custom notification sounds - I would encourage testing on a different OEM, if possible a Google Pixel, to confirm this.

**Comment by renznamoc21** [comment] 2020-07-13 14:43
Thank you for your fast reply
It may confirmed that android OEMs does not allow custom notification sound, i tested also in OPPO phone still default notification,
unfortunately i wasn't able to test in google pixel , i tried in Google pixel XL emulator but no notification arrived

**Comment by dpa99c** [comment] 2020-08-11 07:28
I will close this as I don't believe any action can be taken on the plugin's part, and label it as a caveat

**Closed by dpa99c** 2020-08-11 07:28 UTC
Labels: android, runtime issue, support

**Comment by SergioZhydecky** [comment] 2020-11-03 13:02
Hi. I still have this issue. I can't get custom sound to work. I tested on Huawai P20 lite Android 8. Xiaomi Redmi 9 and on emulators

**Comment by gs-nasc** [comment] 2021-06-08 15:30
@SergioZhydecky have you checked if the app is allowed to sound the notification?
