### ISSUE TITLE
Build failed for IOS

### ISSUE THREAD

**Issue by weihangswtch** [dpa99c/cordova-plugin-firebasex#518] opened 2020-09-22 04:11 UTC
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [ ] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

> 	CompileC /Users/EL-CAPITAN-2016/Library/Developer/Xcode/DerivedData/PowerCharge-bsmgqqwrklepxgcncklbzwngsixq/Build/Intermediates.noindex/PowerCharge.build/Release-iphonesimulator/PowerCharge.build/Objects-normal/x86_64/FirebasePlugin.o /Users/EL-CAPITAN-2016/Documents/swtch/new_pc_iOS/dev_powercharge_iOS/platforms/ios/PowerCharge/Plugins/cordova-plugin-firebasex/FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

Occurred when I ran `cordova build ios --release --prod` 
However it shows **Build Succeed** when I ran `cordova build ios --prod`
for both my project & [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test)

 Potential solution I have tried:
1. `pod repo update && pod install`
2. `sudo gem install cocoapods-dependencies`
3. `pod dependencies`
4. Removed `node_modules`&`platform`&`plugins` and re-added the cli version including `11.0.1-cli` `10.2.0-cli` `9.1.1-cli`
5. I tried `cordova-ios@5.1.1`&`cordova-ios@6.0.0`

But cannot solve this issue.

**Expected behavior:**

**Build Succeed** with the `--release` flag
**Steps to reproduce:**

I followed CLI build instructions:

1. `npm install`
2. `cordova platform add ios`
3. `cordova build ios --release --prod`

**Screenshots**

<img width="976" alt="Screen Shot 2020-09-21 at 11 55 51 PM" src="https://user-images.githubusercontent.com/66751254/93842788-02ad5880-fc66-11ea-9a18-d2f0f14c1c64.png">

**Environment information**

- Cordova CLI version 
	- `cordova -v`
 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- `cordova platform ls`
Installed platforms:
 ios 6.0.0

- Podfile 
```
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
use_frameworks!
target 'PowerCharge' do
        project 'PowerCharge.xcodeproj'
        pod 'Firebase/Core', '6.28.1'
        pod 'Firebase/Auth', '6.28.1'
        pod 'Firebase/Messaging', '6.28.1'
        pod 'Firebase/Performance', '6.28.1'
        pod 'Firebase/RemoteConfig', '6.28.1'
        pod 'FirebaseFirestore', :tag => '6.28.1', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git'
        pod 'Firebase/Crashlytics', '6.28.1'
        pod 'GoogleSignIn', '5.0.2'
end
```

- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
```
com.googlemaps.ios 3.9.0 "Google Maps SDK for iOS"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-call-number 1.0.1 "Cordova Call Number Plugin"
cordova-plugin-camera 5.0.0 "Camera"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-customurlscheme 5.0.2 "Custom URL scheme"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 10.2.0-cli "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-nativegeocoder 3.4.1 "NativeGeocoder"
cordova-plugin-safariviewcontroller 1.6.0 "SafariViewController"
cordova-plugin-splashscreen 6.0.0 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 5.1.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
iOS devices
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
iOS 11.0
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
v11.4.0
- XCode version
Version 12.0 (12A7209)

**Related code:**
N/A

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

I know this issue has been reported before but none of the solution worked, please help me.
Thank you for your great effort and contribution to this project.

**Comment by dpa99c** [comment] 2020-09-22 04:30
This is a likely duplicate of https://github.com/dpa99c/cordova-plugin-firebasex/issues/515, however this cannot be confirmed because the console extracts you have posted do not contain the actual cause of the build failure.
Please follow the suggestions in the linked issue including validation against the example project. 

Closing as this is a support issue specific to you, not a plugin bug.

**Closed by dpa99c** 2020-09-22 04:30 UTC
