### ISSUE TITLE
FirebasePlugin.h:4:9: fatal error: module 'FirebaseFirestore' not found

### ISSUE THREAD

**Issue by jpdelmundo** [dpa99c/cordova-plugin-firebasex#735] opened 2022-05-27 10:13 UTC
cordova: 11.0.0
cordova-ios: 6.2.0
cordova-plugin-firebasex: 14.1.0 (also tried 14.1.0-cli)
xcode: 13.4

Error:

In file included from /Users/< user >/< project >/cordova/platforms/ios/< app name >/Plugins/cordova-plugin-firebasex/AppDelegate+FirebasePlugin.m:2:
/Users/< user >/< project >/cordova/platforms/ios/< app name >/Plugins/cordova-plugin-firebasex/FirebasePlugin.h:4:9: fatal error: module 'FirebaseFirestore' not found
@import FirebaseFirestore;

Tried the following but didn't fix it:
- `pod repo update` then `pod install` in the platforms/ios dir
- `pod deintegrate` and `pod install`
- `cordova platform rm/add ios`
- `cordova plugin rm/add cordova-plugin-firebasex`
- `cordova clean`
- Xcode clean build folder

**Comment by subbuy** [comment] 2022-05-28 00:08
> cordova: 11.0.0 cordova-ios: 6.2.0 cordova-plugin-firebasex: 14.1.0 (also tried 14.1.0-cli) xcode: 13.4
> 
> Error:
> 
> In file included from /Users/< user >/< project >/cordova/platforms/ios/< app name >/Plugins/cordova-plugin-firebasex/AppDelegate+FirebasePlugin.m:2: /Users/< user >/< project >/cordova/platforms/ios/< app name >/Plugins/cordova-plugin-firebasex/FirebasePlugin.h:4:9: fatal error: module 'FirebaseFirestore' not found @import FirebaseFirestore;
> 
> Tried the following but didn't fix it:
> 
> * `pod repo update` then `pod install` in the platforms/ios dir
> * `pod deintegrate` and `pod install`
> * `cordova platform rm/add ios`
> * `cordova plugin rm/add cordova-plugin-firebasex`
> * `cordova clean`
> * Xcode clean build folder

Ran into same issue. Went back to cordova-plugin-firebasex: 14.0.0 and seems to compile in xcode.

**Comment by FalconKul** [comment] 2022-05-30 07:02
I have seen the same issue, I resolve it by manually changing Podfile to force download Firestore. 
Below is my step to resolve it:
1. Goto platform/ios and remove Podfile.lock
2. Remove Pods folder
3. Open Podfile and replace `pod 'FirebaseFirestore', :tag => '9.1.0', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git'` by `pod 'Firebase/Firestore', '9.1.0'`
4. `pod install`

**Comment by jpdelmundo** [comment] 2022-05-31 09:32
So, I discovered a workaround, at least in my case. I am using an M1 Mac and I saw a suggestion to run Xcode on Rosetta. After I doing that, Xcode now successfully builds the app.

Basically:
1. Quit Xcode if it's running
2. Open the Applications folder
3. Right-click on Xcode
4. Choose Get Info (there's maybe another step to see the "Get Info" option)
5. Tick/check on "Open using Rosetta"
6. Run Xcode again to build the app (or your cordova build cli)

**Comment by dpa99c** [comment] 2022-05-31 10:05
Seems like this issue might be specific to Apple Silicon: https://github.com/invertase/firestore-ios-sdk-frameworks/issues/51

The reason for not using the Firestore Pod directly from the Firebase SDK is that it needs to be compiled from scratch which can take a very long time - upwards of 30 minutes on an old Mac:
https://github.com/dpa99c/cordova-plugin-firebasex/issues/407

This was resolved by using a git repo which contains a pre-compiled version of Firestore which significantly decreases build time:
https://github.com/dpa99c/cordova-plugin-firebasex/pull/440

But it seems from the issue raised against `firestore-ios-sdk-frameworks` there might be a problem with this on Apple Silicon.
Hence running in Rosetta resolves it as it will handle code compiled for Intel architecture.

**Comment by dpa99c** [comment] 2022-05-31 13:13
I am using an Intel-based Mac and `cordova-plugin-firebasex@14.0.0` using Firebase iOS SDK v9.1.0 builds fine for me so I'm still thinking the issue is specific to Apple Silicon.

Can someone with an M1 Mac try adding `use_frameworks!` to the `Podfile` and see if that resolves the issue?
It's documented as a breaking change in the [Firebase iOS SDK v9.0.0 release notes](https://firebase.google.com/support/release-notes/ios#version_900_-_may_3_2022) but doesn't seem required for an Intel Mac so maybe it's a specific requirement for Apple Silicon Macs.

**Comment by tzappia** [comment] 2022-05-31 22:31
@dpa99c note you already have `<pods use-frameworks="true">` in plugin.xml, so `use_frameworks!` is already being added to the Podfile.

On my M1 Mac, I get this error using `cordova build`, but my build runs successfully in Xcode immediately afterwards without making any code changes or using Rosetta. I am using branch `14.1.0-cli`

```
/Users/tzappia/workspace/tovi/app/platforms/ios/TOVI/Plugins/cordova-plugin-firebasex/FirebasePlugin.h:4:9: fatal error: module 'FirebaseFirestore' not found
@import FirebaseFirestore;
 ~~~~~~~^~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by Birowsky** [comment] 2022-06-01 11:42
I have this issue on GitHub Actions - Mac runner. They don't use M1, do they?

**Comment by jpdelmundo** [comment] 2022-06-03 03:17
> This was resolved by using a git repo which contains a pre-compiled version of Firestore which significantly decreases build time:
> #440

@dpa99c Is there a pre-compiled version for Apple Silicon, if none, then this is still a problem. Now, if there is a pre-compiled version for Apple Silicon, is it the version being installed by cocoapods?

It looks like @FalconKul's suggestion above is still the solution to this.

**Comment by pinguluk** [comment] 2022-06-07 11:24
> EDIT: For some reason, this is not working for me anymore. Use @FalconKul's suggestion above. I'm leaving this here in case it might be helpful to some.
> 
> So, I discovered a workaround, at least in my case. I am using an M1 Mac and I saw a suggestion to run Xcode on Rosetta. After I doing that, Xcode now successfully builds the app.
> 
> Basically:
> 
> 1. Quit Xcode if it's running
> 2. Open the Applications folder
> 3. Right-click on Xcode
> 4. Choose Get Info (there's maybe another step to see the "Get Info" option)
> 5. Tick/check on "Open using Rosetta"
> 6. Run Xcode again to build the app (or your cordova build cli)

This builds the app fine on emulators, but the app itself is stuck on the splashscreen, without any error

**Comment by roundlakedan** [comment] 2022-06-07 12:54
Just to clarify previous comments/suggestions - I'm still doing my builds on an Intel-based mbp and it's throwing the "Module 'FirebaseFirestore' not found" error when I try to analyze the app. I'm able to build it, and even run it on my local device. But I can't get it uploaded to the app store as it won't pass basic checks.

**Comment by Franco-Alejandro** [comment] 2022-06-17 11:20
I'm using intel and I'm running into this error when trying to archive from Xcode, I'll update if I find something (using this plugin on the latest version)

**Comment by Franco-Alejandro** [comment] 2022-06-17 13:28
Ok, so far I had to use the pod directly, because it was blocking my update.

I've tried a couple of things that did not work. A weird thing that did happen to mes was that the build DID WORK on an emulator and my device. But when I tried building the ipa for release, it got stuck here.

**Comment by raymondelferink** [comment] 2022-06-17 13:53
I have tried all the suggestion, but to no avail. Version 14.0.0 works fine, 14.1.0 doesn't. I use the same macbook pro (2019), same code, same everything. Both versions use the pre-compiled version of the Firestore Pod mentioned here: https://github.com/dpa99c/cordova-plugin-firebasex/pull/737#issuecomment-1141884263
This is not my cup of tea, so I'm reverting to v14.0.0 for now. I'll keep an watching this space though:-)

**Comment by Franco-Alejandro** [comment] 2022-06-17 14:05
It might be possible that the error is not the plugin itself but rather the pre-compiled version?

**Comment by peitschie** [comment] 2022-07-11 04:37
So... some progress here, this seems to be tied to the iOS deployment target for the FirebaseFirestore being `iOS 10.0`. If I go into the cordova workspace file and manually bump JUST this dependency to `iOS 11.0`, then this all builds correctly:

![image](https://user-images.githubusercontent.com/1052079/178189484-729cf42c-f49d-420d-85c2-438f3ff6a7de.png)

I'll update if I get a better way to set this automatically...

**Comment by ZaLiTHkA** [comment] 2022-07-11 06:00
@peitschie do you know of a way to do that within a CI environment? I'm trying to release an update to a mobile app, but I don't have access to a Mac, so I can only build for iOS in the cloud (aka: on somebody else's machine).

**Comment by peitschie** [comment] 2022-07-11 06:33
Not the prettiest... but here's a cordova hook that does the job for me:

Added to `ios` platform in `config.xml`:
```
<hook src="hooks/firebaseDeploymentTargetFix.js" type="before_prepare" />
```

In a file in `hooks/firebaseDeploymentTargetFix.js` in the root of your cordova project:
```
#!/usr/bin/env node

// Workaround for https://github.com/dpa99c/cordova-plugin-firebasex/issues/735
// FirebaseFirestore appears to require iOS deployment target >= 11.0

const fs = require("fs");
const path = require("path");
const execa = require("execa");

module.exports = (context) => {
  const platformPath = path.resolve(context.opts.projectRoot, "platforms/ios");
  const podfilePath = path.resolve(platformPath, "Podfile");

  if (!fs.existsSync(podfilePath)) {
    console.log(`'${podfilePath}' does not exist. Firebase deployment fix skipped.`);
    return;
  }

  let podfileContent = fs.readFileSync(podfilePath, "utf-8");
  if (podfileContent.indexOf("post_install") == -1) {
    podfileContent += `

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'FirebaseFirestore'
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
end`;

    fs.writeFileSync(podfilePath, podfileContent, "utf-8");

    return execa("pod", ["install", "--verbose"], {
      cwd: platformPath,
    });
  }
};
```

**Comment by ZaLiTHkA** [comment] 2022-07-11 07:37
thanks so much for the prompt response.. 👍🏼 

> Added to `ios` platform in `config.xml`:
> 
> ```
> <hook src="hooks/firebaseDeploymentTargetFix.js" type="before_prepare" />
> ```

however, Appflow is making things stupendously difficult here:

> Cordova hooks are specified in your `config.xml` and when used with the Cordova CLI will execute scripts. Appflow however uses Gym to compile your Application, so Cordova hooks **will not** run with the exception of `after_platform_add` and `after_prepare`.
>
> [[source](https://ionic.io/docs/appflow/cookbook/hooks#cordova-hooks)]

---

just for the sake of testing, I switched the hook trigger from `before_prepare` to `after_platform_add`, thinking along the lines of "the platform needs to be added first anyway, so maybe this will happen before the 'prepare' stage. however, this simply results in a different error:

```
▸ Compiling FirebasePlugin.m

⚠️  /Users/ionic-cloud-team/builds/<GITLAB_PATH_REDACTED>/platforms/ios/LIVE!/Plugins/cordova-plugin-firebasex/FirebasePlugin.h:8:49: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]

- (void)setAutoInitEnabled:(CDVInvokedUrlCommand*)command;
                                                ^
```

I **don't** want to hijack this issue with discussions regarding Cordova Hooks in Ionic Appflow, so I'll go do some more digging now and see what else I can find.

**Comment by peitschie** [comment] 2022-07-11 07:44
wait!! I mis-typed that... should be `after_prepare`

Can you see if this works?

**Comment by ZaLiTHkA** [comment] 2022-07-11 09:19
FWIW: setting the iOS platform `deployment-target` preference to `11.0` didn't change anything from my previous message..

> @ZaLiTHkA that sounds related to this: [invertase/firestore-ios-sdk-frameworks#52](https://github.com/invertase/firestore-ios-sdk-frameworks/pull/52) I suspect you can extend the hook above to apply similar steps as the patch there.

..so I will dig into this one now then.

thank you for the assistance, greatly appreciate it. 🖖🏼

**Comment by peitschie** [comment] 2022-07-11 23:24
@Leffe108 this workaround here should fix the issue for you: https://github.com/dpa99c/cordova-plugin-firebasex/issues/735#issuecomment-1180019463

**Closed** 2022-07-20 13:53 UTC

**Comment by dpa99c** [comment] 2022-07-20 14:37
`cordova-plugin-firebasex@14.2.0` has just been published to npm and should resolve this.
By default, the plugin will now use the standard pod for Firestore unless you optionally specify the plugin variable `IOS_USE_PRECOMPILED_FIRESTORE_POD=true` at install time, in which case the pre-compiled version will be used.

If you have issues with an existing project, run these commands from `platforms/ios/` as [suggested here](https://stackoverflow.com/a/59547863/777265):
```
pod deintegrate
pod setup
pod install
```

Note that in the version you can also specify `IOS_FIREBASE_SDK_VERSION` to override the version of the Firebase iOS SDK pinned in `plugin.xml`.

**Comment by aliexalter** [comment] 2022-07-22 13:35
How can I fix this error on ionic appflow ?
I am using 4.2.0-cli version.

**Comment by dpa99c** [comment] 2022-07-22 14:33
@aliexalter This plugin ([as noted](https://github.com/dpa99c/cordova-plugin-firebasex#build-environment-notes)) relies on Cordova Hook scripts to configure the native platform projects. Ionic Appflow [does not support](https://ionic.io/docs/appflow/cookbook/hooks#cordova-hooks) all of the hooks used by this plugin so it may not work correctly in that build environment.
