### ISSUE TITLE
Failed to install 'cordova-plugin-firebasex'

### ISSUE THREAD

**Issue by hoangnk121** [dpa99c/cordova-plugin-firebasex#108] opened 2019-08-20 10:57 UTC
When I add platform (ios) (Android worked):
`ionic cordova platform add ios`
I got error:
```
Running command: pod install --verbose

[!] The `HMP [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-HMP/Pods-HMP.debug.xcconfig'. This can lead to problems with the CocoaPods installation


[!] The `HMP [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-HMP/Pods-HMP.release.xcconfig'. This can lead to problems with the CocoaPods installation

Failed to install 'cordova-plugin-firebasex': Error: ENOENT: no such file or directory, open '/Users/hoangnk121/Projects/HMP-Mobile/HMP/platforms/ios/
                HMP
        .xcodeproj/project.pbxproj'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:348:35)
    at pbxProject.parseSync (/Users/hoangnk121/Projects/HMP-Mobile/HMP/node_modules/xcode/lib/pbxProject.js:61:28)
    at Object.removeShellScriptBuildPhase (/Users/hoangnk121/Projects/HMP-Mobile/HMP/plugins/cordova-plugin-firebasex/scripts/ios/helper.js:87:22)
    at /Users/hoangnk121/Projects/HMP-Mobile/HMP/plugins/cordova-plugin-firebasex/scripts/ios/after_plugin_install.js:8:16
    at /Users/hoangnk121/Projects/HMP-Mobile/HMP/plugins/cordova-plugin-firebasex/scripts/ios/helper.js:19:13
    at /Users/hoangnk121/Projects/HMP-Mobile/HMP/plugins/cordova-plugin-firebasex/scripts/lib/utilities.js:27:11
    at Parser.<anonymous> (/Users/hoangnk121/Projects/HMP-Mobile/HMP/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:197:13)
    at SAXParser.onclosetag (/Users/hoangnk121/Projects/HMP-Mobile/HMP/node_modules/xml2js/lib/parser.js:261:26)
ENOENT: no such file or directory, open '/Users/hoangnk121/Projects/HMP-Mobile/HMP/platforms/ios/
                HMP
        .xcodeproj/project.pbxproj'
```

Try remove platforms, plugins, re-install but still not working.

**Comment by dlredden** [comment] 2019-08-20 23:23
`Running command: pod install --verbose

[!] The `Pool League [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Pool League/Pods-Pool League.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Pool League [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Pool League/Pods-Pool League.release.xcconfig'. This can lead to problems with the CocoaPods installation

Failed to install 'cordova-plugin-firebasex': Error: ENOENT: no such file or directory, open '/Users/dl/repos/LeagueCentral/platforms/ios/[object Object].xcodeproj/project.pbxproj'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at pbxProject.parseSync (/Users/dl/repos/LeagueCentral/node_modules/xcode/lib/pbxProject.js:61:28)
    at Object.removeShellScriptBuildPhase (/Users/dl/repos/LeagueCentral/plugins/cordova-plugin-firebasex/scripts/ios/helper.js:87:22)
    at /Users/dl/repos/LeagueCentral/plugins/cordova-plugin-firebasex/scripts/ios/after_plugin_install.js:8:16
    at /Users/dl/repos/LeagueCentral/plugins/cordova-plugin-firebasex/scripts/ios/helper.js:19:13
    at /Users/dl/repos/LeagueCentral/plugins/cordova-plugin-firebasex/scripts/lib/utilities.js:27:11
    at Parser.<anonymous> (/Users/dl/repos/LeagueCentral/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:182:13)
    at SAXParser.onclosetag (/Users/dl/repos/LeagueCentral/node_modules/xml2js/lib/parser.js:261:26)
ENOENT: no such file or directory, open '/Users/dl/repos/LeagueCentral/platforms/ios/[object Object].xcodeproj/project.pbxproj'`

**Comment by dlredden** [comment] 2019-08-21 14:43
My issue turned out to be related to the `<name></name>` tab when the `short` attribute was used i.e. `<name>My App</name>` works but `<name short="MyApp">My App</name>` broke this step. I'll open another issue and PR to fix it.

**Comment by dpa99c** [comment] 2019-08-30 08:28
Fixed by PR #115 which will shortly be released in v6.0.8

**Comment by dpa99c** [comment] 2019-08-30 08:32
On re-reading, PR #115 fixes #114 which is different from your issue @hoangnk121 

It looks like the script cannot find your Xcode project. Please confirm the correct path to your `project.pbxproj` - the script is looking for `/Users/hoangnk121/Projects/HMP-Mobile/HMP/platforms/ios/
                HMP
        .xcodeproj/project.pbxproj`

Also check you have no non-latin characters in your app name as this can cause path issues.

**Comment by dpa99c** [comment] 2019-09-04 07:48
Closed due to no response

**Closed by dpa99c** 2019-09-04 07:48 UTC
Labels: awaiting response, build issue, ios

**Comment by Joaovtrc** [comment] 2019-11-12 20:38
> Closed due to no response

I was having the same issue as him, figured out it was because I was using [cordova-plugin-app-name](https://github.com/blakgeek/cordova-plugin-app-name) with the name 'Colégio Sion', maybe it is because of the Acute accent on the 'Colégio' word?

**Comment by dbessa1** [comment] 2021-05-05 16:45
this worked for me too. Thank Joaovtrc

**Comment by Bishoy-Samy** [comment] 2021-05-29 16:54
when I am installing the plugin I get this while my name tag is <name>AlMashreq</name>

[!] The `AlMashreq [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-AlMashreq/Pods-AlMashreq.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `AlMashreq [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-AlMashreq/Pods-AlMashreq.release.xcconfig'. This can lead to problems with the CocoaPods installation



[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

then when trying to build from the cli... it fails... what is the cause of this and how to solve it... thanks in advance.
