### ISSUE TITLE
(iOS) Sometimes Push Messages don't arrive

### ISSUE THREAD

**Issue by HansKrywaa** [dpa99c/cordova-plugin-firebasex#368] opened 2020-04-15 08:43 UTC
# Bug report

**Current behavior:**

Some of our Testers mentioned that they often have a Problem with the iOS App, wehere Push Messages are not arriving. Restarting the App or Restarting the Smartphone worked sometimes, but this shouldn't be the Solution. I noticed this Behavior also, but i'm not able to reproduce it with some strict steps. 

**Expected behavior:**

I want the Push Messages to always arrive correctly. I know you need way more Info to handle this, so how can i help you? Are there any Breakpoints i can debug if this happens to me again? Any Line in Code that should always be executed on a new Message? So i can debug there then and tell you what happens?

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `Installed platforms: android 8.1.0 ios 5.1.1`
- Plugins & versions installed in project (including this plugin)
  ```
  call-number 0.0.2 "Cordova Call Number Plugin"
  cordova-background-geolocation 3.6.2 "BackgroundGeolocation"
  cordova-clipboard 1.3.0 "Clipboard"
  cordova-open-native-settings 1.5.2 "Native settings"
  cordova-plugin-advanced-background-mode 1.1.0 "BackgroundMode"
  cordova-plugin-advanced-http 2.4.1 "Advanced HTTP plugin"
  cordova-plugin-advanced-nativeaudio 1.0.2 "Cordova Native Audio"
  cordova-plugin-advanced-websocket 1.1.5 "Cordova advanced websocket plugin"
  cordova-plugin-android-permissions 1.0.2 "Permissions"
  cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
  cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
  cordova-plugin-app-version 0.1.9 "AppVersion"
  cordova-plugin-appavailability 0.4.2 "AppAvailability"
  cordova-plugin-appcenter-crashes 0.5.1 "App Center Crashes for Cordova"
  cordova-plugin-appcenter-shared 0.5.1 "App Center shared code for Cordova"
  cordova-plugin-apprate 1.5.0 "AppRate"
  cordova-plugin-background-fetch 6.0.5 "CDVBackgroundFetch"
  cordova-plugin-badge 0.8.8 "Badge"
  cordova-plugin-bluetoothle 4.5.10 "Bluetooth LE"
  cordova-plugin-camera 4.1.0 "Camera"
  cordova-plugin-contacts 3.0.1 "Contacts"
  cordova-plugin-device 2.0.3 "Device"
  cordova-plugin-dfu-update 1.0.4 "DFU Update"
  cordova-plugin-dialogs 2.0.2 "Notification"
  cordova-plugin-email-composer 0.9.2 "EmailComposer"
  cordova-plugin-facebook4 6.4.0 "Facebook Connect"
  cordova-plugin-file 6.0.2 "File"
  cordova-plugin-file-opener2 3.0.0 "File Opener2"
  cordova-plugin-file-transfer 1.7.1 "File Transfer"
  cordova-plugin-firebasex 9.0.3 "Google Firebase Plugin"
  cordova-plugin-flic-lib 1.1.1 "Flic"
  cordova-plugin-google-analytics 1.9.0 "Google Universal Analytics Plugin"
  cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
  cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
  cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
  cordova-plugin-ionic-webview 4.2.0 "cordova-plugin-ionic-webview"
  cordova-plugin-ios-disableshaketoedit 1.0.0 "iOS Disable Shake to Edit"
  cordova-plugin-ios-keychain 3.0.1 "KeyChain Plugin for Cordova iOS"
  cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
  cordova-plugin-market 1.2.0 "Market"
  cordova-plugin-nativestorage 2.3.2 "NativeStorage"
  cordova-plugin-network-information 2.0.2 "Network Information"
  cordova-plugin-play-default-sounds 1.0.0 "PlayDefaultSounds"
  cordova-plugin-safariviewcontroller 1.6.0 "SafariViewController"
  cordova-plugin-secure-preferences 1.4.0 "Secure Preferences"
  cordova-plugin-sms-retriever-manager 0.0.2 "Device"
  cordova-plugin-splashscreen 5.0.3 "Splashscreen"
  cordova-plugin-statusbar 2.4.3 "StatusBar"
  cordova-plugin-timer 1.0.1 "Native timer"
  cordova-plugin-vibration 3.1.1 "Vibration"
  cordova-plugin-whitelist 1.3.4 "Whitelist"
  cordova-plugin-x-socialsharing 5.6.4 "SocialSharing"
  cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
  cordova-sqlite-storage 5.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
  cordova-support-google-services 1.4.0 "cordova-support-google-services"
  cordova.plugins.diagnostic 5.0.1 "Diagnostic"
  es6-promise-plugin 4.2.2 "Promise"
  ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
  ```
  </details>
- Dev machine OS and version, e.g.
    - OSX
        - `sProductName:	Mac OS X ProductVersion:	10.15.4 BuildVersion:	19E287`
        
_Runtime issue_
- Device details
    - Mostly tested on iPhone 6s and iPhone 11 Pro

**Comment by dpa99c** [comment] 2020-04-15 09:40
I would suggest doing the following:
- Build and test in the [example project app](https://github.com/dpa99c/cordova-plugin-firebasex-test)
    - this is a known and tested codebase that tests this plugin in isolation
    - as there are many other plugins in your project which could cause conflicts
- Confirm whether notifications fail to appear when the app is in the foreground or in the background
	- When the app is in the foreground, the plugin constructs a custom notificiation
		- so monitor the application log for errors
	- When the app is in the background/not running, the display of notifications is handled by the OS - no plugin code is executed
		- in which case there will be no application log entries, so monitor the system log for errors 
- Test with known message payloads
	- It's possible for invalid message payloads to cause notifications not to be displayed (both in background and foreground)
	- Check if a specific message/type of message is causing notifications not to appear


Closing this for now as there's not enough detail for it to be a useful issue and there could be many possible causes that aren't related to this plugin's code.

But if after investigating you are able to narrow down the cause and believe it to be a bug in the plugin code, please open a new issue with full details including if possible steps to reproduce the issue in the example project app.

**Closed by dpa99c** 2020-04-15 09:40 UTC
