### ISSUE TITLE
Build for iOS error: fatal error: 'Firebase.h' file not found

### ISSUE THREAD

**Issue by antoniogenaro** [dpa99c/cordova-plugin-firebasex#334] opened 2020-03-10 13:20 UTC
# Bug report

**Current behavior:**

When I build a project for iOS (in Android it works fine), I get the following error

```
/Users/x/platforms/ios/x/Plugins/cordova-plugin-firebasex/FirebasePlugin.h:3:9: fatal error: 'Firebase.h' file not found
#import "Firebase.h"
...
The following build commands failed:
        CompileC /Users/x/Library/Developer/Xcode/DerivedData/x-dpztifmzhyzdgtcfmzrdsjkflmbv/Build/Intermediates.noindex/x.build/Debug-iphonesimulator/x.build/Objects-normal/x86_64/FirebasePlugin.o /Users/x/platforms/ios/x/Plugins/cordova-plugin-firebasex/FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
```

I'm using the plugin in Ionic with `@ionic-native/firebase-x`, and just added the following code in app.component.ts

```ts
import { FirebaseX } from '@ionic-native/firebase-x/ngx';
...
constructor(private firebase: FirebaseX) {}
...
this.firebase.setScreenName('root');
```

**Expected behavior:**
The project should compile in iOS

**Steps to reproduce:**
Build the project for iOS with this plugin

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `Installed platforms: android 8.1.0 ios 5.1.1`
- Plugins & versions installed in project (including this plugin)
    - `cordova-plugin-actionsheet 2.3.3 "ActionSheet"`
    - `cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"`
    - `cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"`
    - `cordova-plugin-device 2.0.2 "Device"`
    - `cordova-plugin-dialogs 2.0.2 "Notification"`
    - `cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"`
    - `cordova-plugin-firebasex 8.1.1 "Google Firebase Plugin"`
    - `cordova-plugin-geolocation 4.0.2 "Geolocation"`
    - `cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"`
    - `cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"`
    - `cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"`
    - `cordova-plugin-safariviewcontroller 1.6.0 "SafariViewController"`
    - `cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"`
    - `cordova-plugin-splashscreen 5.0.2 "Splashscreen"`
    - `cordova-plugin-statusbar 2.4.2 "StatusBar"`
    - `cordova-plugin-whitelist 1.3.3 "Whitelist"`
    - `cordova-sqlite-storage 3.4.1 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"`
    - `cordova.plugins.diagnostic 5.0.1 "Diagnostic"`
    - `es6-promise-plugin 4.2.2 "Promise"`
    - `ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"`
    - `uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator`
- Dev machine OS and version, e.g.
    - OSX
        - `ProductName:    Mac OS X ProductVersion: 10.14.6 BuildVersion:   18G3020`
	
_iOS build issue:_
- Node JS version
    - `v10.16.0`
- XCode version
    - `Version 11.3 (11C29) `

Thanks in advance!

**Comment by dpa99c** [comment] 2020-03-10 13:34
Duplicate of #254, etc

- Install/update local Cocoapods repo
- Validate build environment using [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test)

**Closed by dpa99c** 2020-03-10 13:34 UTC
