### ISSUE TITLE
Adding firebasex to existing app does not install background service when app is updated on iOS

### ISSUE THREAD

**Issue by klimentLambevski** [dpa99c/cordova-plugin-firebasex#592] opened 2021-02-23 11:14 UTC
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

The plugin works as expected on new install of the app but when existing app is updated the plugin does not work. I checked in settings and "background app refresh" and "notifications" sections are not there. 
`FirebasePlugin.hasPermission` is called but never fires success or error callbacks.
When the new version is installed from app store it works as expected

**Expected behavior:**
Plugin to function as expected when app is updated

**Steps to reproduce:**
Existing app on appstore without FirebasePlugin added.
Add FirebasePlugin to new version of the app
Update the app from app store

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `10.0.0`
- Cordova platform version
	- ` ios 6.2.0`
- Plugins & versions installed in project (including this plugin)
    - 
    cc.fovea.cordova.purchase 10.5.3 "Purchase"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 3.0.0 "cordova-plugin-androidx"
cordova-plugin-camera 5.0.0 "Camera"
cordova-plugin-facebook4 6.4.0 "Facebook Connect"
cordova-plugin-firebasex 11.0.3 "Google Firebase Plugin"
cordova-plugin-native-spinner 1.1.3 "Native Spinner"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-sign-in-with-apple 0.1.2 "cordova-plugin-sign-in-with-apple"
cordova-plugin-splashscreen 6.0.0 "Splashscreen"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 6.0.2 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"

_Runtime issue_
- Device details
    - iPhone XS Max
- OS details
    - iOS 14.4

**Comment by dpa99c** [comment] 2021-03-26 09:22
This plugin wraps Firebase Cloud Messaging to provide remote notifications functionality and FCM itself using Apple's APNS service to send the notifications. Therefore no background service is installed by this plugin; it relies on existing functionality of the iOS operating system to deliver push notifications to the device while an app is not running/in the background.

If the "notifications" section is not showing up in the Settings app for your app, this means remote notifications permission has not been granted.
If `hasPermission` is failing to callback with either success or failure, this would indicate to me that the [`getNotificationSettingsWithCompletionHandler` completion handler](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/FirebasePlugin.m#L266) is not getting invoked.
I'm unsure what would cause that but it's possible there's a problem with your APNS configuration.
Whatever the cause, it's not within the scope of this plugin to programmatically resolve your issue and therefore I'm closing this issue on that basis.
However if you're able to provide evidence this is a generic issue which will affect all plugin users (vs being specific to your own app configuration), I'll be happy to reopen this.

**Closed by dpa99c** 2021-03-26 09:22 UTC
