### ISSUE TITLE
Pods GoogleUtilities fatal error

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-plugin-firebasex#453] opened 2020-07-14 21:01 UTC
# Bug report

**CHECKLIST**
- [ ] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [ ] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x ] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x ] I have checked that no similar issues (open or closed) already exist.

Hi Dave, I have combed through stackoverflow, through the plugin docs and other resources and still can't resolve this.  I suspect it has something to do with the Pods < - > Cordova@9/cordova-ios@5 issue or it could be some version compatibility issue since everything is on the latest and greatest.  But I can't be certain either assumption.

Since this is a fresh install on a brand new Mac everything is using the latest and greatest versions of everything.  I also verified all my pods are up to date.  

**Current behavior:**
Build fails during CLI `ionic Cordova build iOS`

** Plugin vs Your own code**
Fresh install on new Mac computer.  Just built the environment, no errors and ported all GOOD code from previous Mac that is working/compiling fine....but on older versions of environment

**Expected behavior:**
clean cli compile

**Steps to reproduce:**
Fails on every build from cli

**Screenshots**

**Environment information**
Ionic:
   Ionic CLI         : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework   : ionic1 1.0.0
   @ionic/v1-toolkit : 1.0.22
Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 32 other plugins)
Utility:
   cordova-res : 0.15.1
   native-run  : not installed
System:
   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v14.5.0 (/usr/local/Cellar/node/14.5.0/bin/node)
   npm        : 6.14.5
   Cocoapods:  1.9.3
   OS         : macOS Catalina
   Xcode      : Xcode 11.5 Build version 11E608c

**Console output**
<details>
Error: 
/Users/rpo/dev/myApp/platforms/ios/Pods/GoogleUtilities/GoogleUtilities/AppDelegateSwizzler/Private/GULAppDelegateSwizzler.h:19:9: fatal error: 
      'GoogleUtilities/AppDelegateSwizzler/Private/GULApplication.h' file not found
#import "GoogleUtilities/AppDelegateSwizzler/Private/GULApplication.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/rpo/dev/myApp/platforms/ios/Pods/GoogleUtilities/GoogleUtilities/AppDelegateSwizzler/Private/GULAppDelegateSwizzler.h:19:9: note: did not find header
      'AppDelegateSwizzler/Private/GULApplication.h' in framework 'GoogleUtilities' (loaded from '/Users/rpo/dev/myApp/platforms/ios/build/emulator')
1 error generated.

<summary>The following build commands failed:
	CompileC /Users/rpo/Library/Developer/Xcode/DerivedData/WHIPSTER-fbocyrfnyhrizhfbhadoplqyjoae/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseAuth.build/Objects-normal/x86_64/FIRAuth.o /Users/rpo/dev/myApp/platforms/ios/Pods/FirebaseAuth/FirebaseAuth/Sources/Auth/FIRAuth.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by Othercarlos93** [comment] 2020-07-14 22:53
I have exactly the same issue, I have the latest Pods installed for Firebase usually the same they comes with the spec of plugin.xml of cordova-plugin-firebasex, yesterday and others past days was build successfully but from today the build failed, with same issue reported for @rolinger

**Comment by keeepon** [comment] 2020-07-14 23:15
Firebase iOS has been updated to 6.28.0.

Firebase iOS Release Notes
https://firebase.google.com/support/release-notes/ios

I fixed the version of Firebase iOS in plugin.xml from 6.27.0 to 6.28.0 and the build was successful.

```
<podspec>
  <config>
    <source url="https://cdn.cocoapods.org/"/>
  </config>
  <pods use-frameworks="true">
    <pod name="Firebase/Core" spec="6.28.0"/>
    <pod name="Firebase/Auth" spec="6.28.0"/>
    <pod name="Firebase/Messaging" spec="6.28.0"/>
    <pod name="Firebase/Performance" spec="6.28.0"/>
    <pod name="Firebase/RemoteConfig" spec="6.28.0"/>
    <pod name="FirebaseFirestore" git="https://github.com/invertase/firestore-ios-sdk-frameworks.git" tag="6.28.0"/>
    <pod name="Firebase/Crashlytics" spec="6.28.0"/>
    <pod name="GoogleSignIn" spec="5.0.2"/>
  </pods>
</podspec>
```

**Comment by rolinger** [comment] 2020-07-15 01:44
@keeepon - what is the path to this file?  I found similar info in the Podfile of the project, but its not the plugin.xml file you are referring to.  And I can't find that one.

**Comment by keeepon** [comment] 2020-07-15 02:12
@rolinger

I am using cordova-plugin-firebasex@10.1.0-cli.
You can find it in plugin.xml for 10.1.0-cli.

https://github.com/dpa99c/cordova-plugin-firebasex/blob/10.1.0-cli/plugin.xml#L126-L140

**Comment by rolinger** [comment] 2020-07-15 02:18
@keeepon - yeah, I think I have been staring at my screen too long and just glazed right over the obvious.  I am on firebasex@10.1.0 too.  I modified the plugin in my root project then removed the platform iOS and readded it again, now its hanging during the `platform add iOS`

Installing "cordova-plugin-firebasex" for ios
Plugin dependency "cordova-plugin-androidx@2.0.0" already fetched, using that version.
Dependent plugin "cordova-plugin-androidx" already installed on ios.
Plugin dependency "cordova-plugin-androidx-adapter@1.1.1" already fetched, using that version.
Dependent plugin "cordova-plugin-androidx-adapter" already installed on ios.
Running command: pod install --verbose
     Cloning into '/var/folders/jh/2c6ccmp12wz91ldjjf44q5b40000gn/T/d20200714-51318-r76e34'...

May have to rebuild my whole project now and try modifying the plugin before its added to my project.

**Comment by driiftkiing** [comment] 2020-07-15 09:44
@keeepon: I have created a [PR](https://github.com/dpa99c/cordova-plugin-firebasex/pull/457) with your change

**Comment by dpa99c** [comment] 2020-07-15 12:47
I can confirm this is caused by the publication of `GoogleUtilities@6.7.0` which is a downstream dependency of the Firebase SDK - [see here](https://github.com/firebase/firebase-ios-sdk/issues/6047) for more info.

Updating the Firebase iOS SDK components to v6.28.0 resolves the issue.

I will merge the PR by @driiftkiing which bumps this plugin to that version and push out a patch release.

Please make sure you update your local pods repo: `pod repo update`

**Comment by rolinger** [comment] 2020-07-15 12:52
I did the manual edit to the plugin suggested by @keeepon and compiled with success.  I will pull the new plugin once available.  Thanks guys.  Since my project had to be completely rebuilt from scratch on a new Mac and I have all the latest and greatest tool versions (npm,ionic, gulp, plugin versions, etc) I  am more than relieved it wasn't my build environment.

**Comment by bhargavas12** [comment] 2020-07-15 12:55
@dpa99c  so we can use the latest firebaseX @10.1.0 with updated firebase ios to 6.28.0. will this resolve the issue ?

**Comment by rolinger** [comment] 2020-07-15 13:01
@bhargavas12 - yes, until the new plugin is available you can edit the `/project/plugins/cordova-plugin-firebasex/plugin.xml` and update any reference to '6.27.0` to `6.28.0`.  Then you will need to `Cordova platform rm iOS` and read `Cordova platform add iOS` to rebuild your project.  Worked for me.

**Comment by dpa99c** [comment] 2020-07-15 13:03
The fix has been published in `cordova-plugin-firebasex@10.1.1` and `cordova-plugin-firebasex@10.1.1-cli`.
Please update to this version.

**Comment by petergrau** [comment] 2020-07-15 13:04
> I can confirm this is caused by the publication of `GoogleUtilities@6.7.0` which is a downstream dependency of the Firebase SDK - [see here](https://github.com/firebase/firebase-ios-sdk/issues/6047) for more info.
> 
> Updating the Firebase iOS SDK components to v6.28.0 resolves the issue.
> 
> I will merge the PR by @driiftkiing which bumps this plugin to that version and push out a patch release.
> 
> Please make sure you update your local pods repo: `pod repo update`

Can we also get an update for 9.1.2 since we are still using that one? #458 should be mergeable for that release. (Just wasn't able to select the correct base.)

**Closed by dpa99c** 2020-07-15 13:03 UTC
Labels: Firebase SDK, build issue, ios

**Comment by bhargavas12** [comment] 2020-07-15 13:50
@dpa99c 
getting this error after updating firebaseX to 10.1.1 and tried 'pod install'

Resource "/Users/temp/Library/Developer/Xcode/DerivedData/project/Build/Products/Debug-iphonesimulator/FirebaseInAppMessaging/InAppMessagingDisplayResources.bundle" not found. Run 'pod install' to update the copy resources script.

** BUILD FAILED **

**Comment by dpa99c** [comment] 2020-07-15 14:23
@bhargavas12 looks like you are using `10.1.1` in a CLI build - use `10.1.1-cli` instead and see [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex#cordova-cli-builds)

**Comment by dpa99c** [comment] 2020-07-15 14:24
@petergrau I have no plans to back-patch old versions (which is time-consuming and messy). 
Please update to the latest version or fork the plugin and amend as you require.

**Comment by rolinger** [comment] 2020-07-15 14:36
@dpa99c - my app compiled from CLI using 'ionic Cordova build iOS`, but from within Xcode, deploying to a simulator or device I am now getting the following.  I have never seen these errors before...my identical project on legacy Mac compiles/deploys just fine, but not on this new Mac - only big difference is the latest firebasex version.:

```
FirebasePlugin[native] LOG: GoogleService-Info.plist found, setup: [FIRApp configureWithOptions]
2020-07-15 08:54:05.466921-0400 MYAPP[57637:2715526] 6.28.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
2020-07-15 08:54:05.480679-0400 MYAPP[57637:2715187] [Firebase/Crashlytics] Version 4.3.0
2020-07-15 08:54:05.556821-0400 MYAPP[57637:2715671] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-07-15 08:54:05.556956-0400 MYAPP[57637:2715535] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-07-15 08:54:05.560051-0400 MYAPP[57637:2715535] [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-07-15 08:54:05.560813-0400 MYAPP[57637:2715535] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-07-15 08:54:05.560841-0400 MYAPP[57637:2715671] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-07-15 08:54:05.561600-0400 MYAPP[57637:2715671] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-07-15 08:54:05.562201-0400 MYAPP[57637:2715535] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-07-15 08:54:05.606837-0400 MYAPP[57637:2715673] 6.28.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
2020-07-15 08:54:05.617248-0400 MYAPP[57637:2715673] 6.28.0 - [Firebase/RemoteConfig][I-RCN000072] New config database created. Resetting user defaults.
2020-07-15 08:54:05.618188-0400 MYAPP[57637:2715673] 6.28.0 - [Firebase/Analytics][I-ACS031025] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2020-07-15 08:54:05.619312-0400 MYAPP[57637:2715673] 6.28.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60602000 started
2020-07-15 08:54:05.619605-0400 MYAPP[57637:2715673] 6.28.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2020-07-15 08:54:05.807947-0400 MYAPP[57637:2715187] *** Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without an application ID. Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-update-plist to set GADApplicationIdentifier with a valid App ID. Google Ad Manager publishers, follow instructions here: https://googlemobileadssdk.page.link/ad-manager-ios-update-plist'
```

And I have validated the Google AdMob publishers app ID is in my plist file in the project root and that it was replicated to all the appropriate resource directories during the build.

**Comment by rolinger** [comment] 2020-07-15 15:00
I found this thread was similar but all my configs seem to be correct.  I then noticed the error was due to the specific `GADApplicationIdentifier` key which was not in my googleservices-info.plist file - it looks like admob SDK is now wrapped up into Firebase and needed a different appID key.  Well, that's what it looks like at least.  So I added it to both the root project plist file and to the project/platforms/iOS/myapp/resources/GoogleServices-Info.plist file and recompiled, **BUT** I am  still getting the same error.

**Comment by dpa99c** [comment] 2020-07-15 15:12
@rolinger I'm not getting this error building the example project.

Here'a reproducible test case using a publicly-available `GoogleService-Info.plist` that also works fine:

	cordova create test com.canary.CanaryApparel && cd test
	curl https://github.coventry.ac.uk/raw/301CEM-1920OCTJAN/301CEM-6957713/master/CanaryApparel/GoogleService-Info.plist -o GoogleService-Info.plist
	cordova plugin add cordova-plugin-firebasex@10.1.1-cli
	cordova platform add ios
	cordova build ios --emulator
	#build succeeds

Open `platforms/ios/HelloCordova.xcworkspace` in Xcode and run:

![Screenshot 2020-07-15 at 16 07 46](https://user-images.githubusercontent.com/2345062/87562379-dd282f80-c6b5-11ea-8481-fcae110a6286.png)

**Comment by rolinger** [comment] 2020-07-15 17:51
@dpa99c   I tried multiple things and couldn't get past the admob issue so ultimately I just dropped admob plugin as we are moving away from ads anyway - we were just hoping to get identical builds on old Mac and new Mac so we knew everything was apples to apples.  But once I did that my project compiled and deployed fine, but that was using @10.1.0.  

I took a break and came back to rebuild one final time and I noticed in rebuilding my project that the new PR is now active `cordova-plugin-firebasex 10.1.1 "Google Firebase Plugin"` and now my project build from command line `ionic Cordova build iOS` is failing with the following error - but in Xcode its compiling and deploying to a simulator just fine.

```
PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/rpo/Library/Developer/Xcode/DerivedData/MYAPP-fbocyrfnyhrizhfbhadoplqyjoae/Build/Intermediates.noindex/MYAPP.build/Debug-iphonesimulator/MYAPP.build/Script-8496B8F4F3071A557F1A846D.sh (in target 'MYAPP' from project 'MYAPP')
    cd /Users/rpo/dev/MYAPP_0.3.0/platforms/ios
    /bin/sh -c /Users/rpo/Library/Developer/Xcode/DerivedData/MYAPP-fbocyrfnyhrizhfbhadoplqyjoae/Build/Intermediates.noindex/MYAPP.build/Debug-iphonesimulator/MYAPP.build/Script-8496B8F4F3071A557F1A846D.sh
/Users/rpo/dev/MYAPP_0.3.0/platforms/ios/Pods/FirebaseFirestore/FirebaseFirestore/Resources/gRPCCertificates-Cpp.bundle
error: Resource "/Users/rpo/Library/Developer/Xcode/DerivedData/MYAPP-fbocyrfnyhrizhfbhadoplqyjoae/Build/Products/Debug-iphonesimulator/FirebaseInAppMessaging/InAppMessagingDisplayResources.bundle" not found. Run 'pod install' to update the copy resources script.
```

From /project/platform/iOS I ran `pod install` again, but there was no change.

This sounds like the cordova@9.0/cordova-ios@5.1.1 issue now...but the previous version (@10.1.0) I manually updated the pod references (in plugin.xml) to 6.28.0 worked and now the new one (@10.1.1) does not.  I have not run any of the @10.x.x-cli versions - or are they new merged and one in the same?

**Comment by rolinger** [comment] 2020-07-15 20:17
@dpa99c - not certain how/what happened, but my install went from @10.1.0-cli to @10.1.1 and I didn't see that it wasn't the `10.1.1-cli` version.  Working now.
