### ISSUE TITLE
FirebasePlugin[native]: EXCEPTION: -[__NSCFNumber objectForKeyedSubscript:]: unrecognized selector sent to instance ...

### ISSUE THREAD

**Issue by DioNNiS** [dpa99c/cordova-plugin-firebasex#224] opened 2019-11-14 04:02 UTC
I'm getting following error when the application is running:

```
FirebasePlugin[native]: EXCEPTION: -[__NSCFNumber objectForKeyedSubscript:]: unrecognized selector sent to instance 0xb635914224b3f68f
(anonymous function) — cordova.js:1509
(anonymous function) — Script Element 19:3
(anonymous function) — cordova.js:1049
(anonymous function) — cordova.js:1073
Global Code — Script Element 19:2
cordova.js:1509
```

Environment:
cordova-lib@9.0.1 with:
  cordova-common@3.2.0
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment:
```
  OS: darwin
  Node: v10.15.1
  npm: 6.10.1

Plugins:
  cordova-admob-sdk
  cordova-plugin-admob-free
  cordova-plugin-androidx
  cordova-plugin-androidx-adapter
  cordova-plugin-badge
  cordova-plugin-console
  cordova-plugin-device
  cordova-plugin-facebook4
  cordova-plugin-firebasex
  cordova-plugin-game-center
  cordova-plugin-local-notification
  cordova-plugin-whitelist
  cordova-promise-polyfill

iOS platform:
  Xcode 11.2.1
  Build version 11B53
```

**Comment by dpa99c** [comment] 2019-11-14 09:16
Please can you specify which plugin API function you are calling and with what parameters in order for this exception to be raised or better still provide a code example or steps to reproduce, if possible in the context of the [example project](https://github.com/dpa99c/cordova-plugin-firebasex) which is a known working codebase.

**Comment by DioNNiS** [comment] 2019-11-18 20:54
there is any specific call. it just appears after 10 seconds or so....

**Comment by dpa99c** [comment] 2019-12-03 12:13
I can't reproduce this and since it doesn't appear to be causing a problem other than appearing in the log as a caught exception, I'm closing this for now.

**Closed by dpa99c** 2019-12-03 12:13 UTC
Labels: ios, more info needed, runtime issue
