### ISSUE TITLE
Firebase Messaging iOS SDK v7.0 will no longer support the FCM Direct Channel API

### ISSUE THREAD

**Issue by urlexnilz** [dpa99c/cordova-plugin-firebasex#409] opened 2020-05-25 09:12 UTC
Hi folks, 

today we received an email from Firebase team that "FCM Direct Channel API" will be marked as deprecated: 

> Firebase Messaging iOS Direct Channel has been used for sending data to apps when they are in the foreground and for upstream messages. The Firebase Messaging iOS SDK v7.0 (slated to be released in September 2020) will no longer support the iOS Direct Channel API. Your app will break if you update to the Firebase Messaging iOS SDK v7.0 without migrating off the iOS Direct Channel API.
We are removing this feature in favor of natively supported messaging features provided by Apple Push Notification Service.

Is there anything in the FirebaseX plugin which needs to be updated to meet the above requirements or is it enough to migrate from legacy to v1 in our backend (-> how the message is send)?

**Comment by dpa99c** [comment] 2020-05-25 09:15
Duplicate of #406

**Closed by dpa99c** 2020-05-25 09:15 UTC
