### ISSUE TITLE
pod error : Not able to add ios Platform in ionic

### ISSUE THREAD

**Issue by kartiksolanki** [dpa99c/cordova-plugin-firebasex#386] opened 2020-05-07 20:46 UTC
I am not able to add ios platform inside my ionic project after installing this plugin. Whenever, I run "sudo ionic cordova platform add ios" I get this error:

CordovaError: Promise rejected with non-error: "/Users/wearesas/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:439:in `help!': \u001b[31m[!] You cannot run CocoaPods as root.\u001b[39m (CLAide::Help)\n" +
  '\n' +
  '\u001b[4mUsage:\u001b[24m\n' +
  '\n' +
  '    $ \u001b[32mpod\u001b[39m \u001b[32mCOMMAND\u001b[39m\n' +
  '\n' +
  '      CocoaPods, the Cocoa library package manager.\n' +
  '\n' +
  '\u001b[4mCommands:\u001b[24m\n' +
  '\n' +
  '    \u001b[32m+ cache\u001b[39m      Manipulate the CocoaPods cache\n' +
  '    \u001b[32m+ env\u001b[39m        Display pod environment\n' +
  '    \u001b[32m+ init\u001b[39m       Generate a Podfile for the current directory\n' +
  '    \u001b[32m+ install\u001b[39m    Install project dependencies according to versions from a\n' +
  '                 Podfile.lock\n' +
  '    \u001b[32m+ ipc\u001b[39m        Inter-process communication\n' +
  '    \u001b[32m+ lib\u001b[39m        Develop pods\n' +
  '    \u001b[32m+ list\u001b[39m       List pods\n' +
  '    \u001b[32m+ outdated\u001b[39m   Show outdated project dependencies\n' +
  '    \u001b[32m+ repo\u001b[39m       Manage spec-repositories\n' +
  '    \u001b[32m+ setup\u001b[39m      Setup the CocoaPods environment\n' +
  '    \u001b[32m+ spec\u001b[39m       Manage pod specs\n' +
  '    \u001b[32m+ update\u001b[39m     Update outdated project dependencies and create new Podfile.lock\n' +
  '\n' +
  '\u001b[4mOptions:\u001b[24m\n' +
  '\n' +
  '    \u001b[34m--silent\u001b[39m     Show nothing\n' +
  '    \u001b[34m--version\u001b[39m    Show the version of the tool\n' +
  '    \u001b[34m--verbose\u001b[39m    Show more debugging information\n' +
  '    \u001b[34m--no-ansi\u001b[39m    Show output without ANSI codes\n' +
  '    \u001b[34m--help\u001b[39m       Show help banner of specified command\n' +
  "\tfrom /Users/wearesas/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:47:in `run'\n" +
  "\tfrom /Users/wearesas/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'\n" +
  "\tfrom /Users/wearesas/.rbenv/versions/2.6.3/bin/pod:23:in `load'\n" +
  "\tfrom /Users/wearesas/.rbenv/versions/2.6.3/bin/pod:23:in `<main>'\n"
    at /usr/local/lib/node_modules/cordova/bin/cordova:29:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[ERROR] An error occurred while running subprocess cordova.

Any idea what am I doing wrong? My plugin version is "cordova-plugin-firebasex": "^9.1.1" and I am using this inside my ionic 5 project.

**Comment by dpa99c** [comment] 2020-05-08 06:57
The problem is clearly stated at the top of your console output:

    You cannot run CocoaPods as root

This is likely due to file permissions, e.g. see [this SO post](https://stackoverflow.com/questions/23190064/cant-run-sudo-pod-install-after-updating-to-cocoapods-0-32-1-with-error-you-ca)

Closing as this is not directly caused by or related to this plugin

**Comment by kartiksolanki** [comment] 2020-05-09 02:11
I am trying to do a fresh install in my ionic project and I get this error while installing plugin:

Installing "cordova-plugin-androidx-adapter" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-firebasex': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/wearesas/Desktop/Covid19/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
pod: Command failed with exit code 1

**Comment by dpa99c** [comment] 2020-05-09 06:12
`Error: pod: Command failed with exit code 1` indicates that the plugin failed to install due to a problem with your Cocoapods installation. Please see https://github.com/dpa99c/cordova-plugin-firebasex#cocoapods

**Closed** 2020-05-09 06:13 UTC
Labels: build issue, ios, support
