### ISSUE TITLE
ios ITMS-90381

### ISSUE THREAD

**Issue by JumBay** [dpa99c/cordova-plugin-firebasex#89] opened 2019-08-13 10:18 UTC
Hi,

I have commented this issue https://github.com/dpa99c/cordova-plugin-firebasex/issues/28, but don't know if you're looking into closed one. 

I constantly get this error from Apple: 

> ITMS-90381: Too many symbol files - These symbols have no corresponding slice in any binary [263D23D5-B581-33A2-888A-34773F96801A.symbols, 28ECC179-42A4-36CE-BC76-C954E663361A.symbols, BA88AC1D-86FF-3E2F-8028-3127412E29CC.symbols, D3E7DBBA-5DA2-3BF4-A0DD-85364E53991C.symbols, D69417C6-7DC5-3C36-9731-D98035C10B75.symbols].

- I've run `cordova plugin add cordova-plugin-firebasex --variable IOS_STRIP_DEBUG=true`
- Did this too: https://stackoverflow.com/questions/25755240/too-many-symbol-files-after-successfully-submitting-my-apps/48518656#48518656
- Change in Xcode `Debug Information Format` to `DWARF`
- I've tried to install `cordova-plugin-cocoapod-supportx` but then when building with Xcode I got this error: `'Firebase.h' file not found`. It seems I don't have any pop dependencies installed: ` pod dependencies` doesn't show any.

Here are all the pod dependencies when I don't install the above plugin:
```
Dependencies
- Crashlytics (3.12.0):
  - Fabric (~> 1.9.0)
- Fabric (1.9.0)
- Firebase/Auth (6.3.0):
  - Firebase/CoreOnly
  - FirebaseAuth (~> 6.1.2)
- Firebase/Core (6.3.0):
  - Firebase/CoreOnly
  - FirebaseAnalytics (= 6.0.2)
- Firebase/CoreOnly (6.3.0):
  - FirebaseCore (= 6.0.3)
- Firebase/Messaging (6.3.0):
  - Firebase/CoreOnly
  - FirebaseMessaging (~> 4.1.0)
- Firebase/Performance (6.3.0):
  - Firebase/CoreOnly
  - FirebasePerformance (~> 3.1.0)
- Firebase/RemoteConfig (6.3.0):
  - Firebase/CoreOnly
  - FirebaseRemoteConfig (~> 4.1.0)
- FirebaseABTesting (3.0.0):
  - FirebaseCore (~> 6.0)
  - Protobuf (~> 3.5)
- FirebaseAnalytics (6.0.2):
  - FirebaseCore (~> 6.0)
  - FirebaseInstanceID (~> 4.2)
  - GoogleAppMeasurement (= 6.0.2)
  - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
  - GoogleUtilities/MethodSwizzler (~> 6.0)
  - GoogleUtilities/Network (~> 6.0)
  - "GoogleUtilities/NSData+zlib (~> 6.0)"
  - nanopb (~> 0.3)
- FirebaseAnalyticsInterop (1.2.0)
- FirebaseAuth (6.1.2):
  - FirebaseAuthInterop (~> 1.0)
  - FirebaseCore (~> 6.0)
  - GoogleUtilities/AppDelegateSwizzler (~> 6.2)
  - GoogleUtilities/Environment (~> 6.2)
  - GTMSessionFetcher/Core (~> 1.1)
- FirebaseAuthInterop (1.0.0)
- FirebaseCore (6.0.3):
  - GoogleUtilities/Environment (~> 6.0)
  - GoogleUtilities/Logger (~> 6.0)
- FirebaseInstanceID (4.2.2):
  - FirebaseCore (~> 6.0)
  - GoogleUtilities/Environment (~> 6.0)
  - GoogleUtilities/UserDefaults (~> 6.0)
- FirebaseMessaging (4.1.1):
  - FirebaseAnalyticsInterop (~> 1.1)
  - FirebaseCore (~> 6.0)
  - FirebaseInstanceID (~> 4.1)
  - GoogleUtilities/AppDelegateSwizzler (~> 6.2)
  - GoogleUtilities/Environment (~> 6.2)
  - GoogleUtilities/Reachability (~> 6.2)
  - GoogleUtilities/UserDefaults (~> 6.2)
  - Protobuf (~> 3.1)
- FirebasePerformance (3.1.0):
  - FirebaseCore (~> 6.0)
  - FirebaseInstanceID (~> 4.2)
  - FirebaseRemoteConfig (~> 4.1)
  - GoogleToolboxForMac/Logger (~> 2.1)
  - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
  - GoogleUtilities/Environment (~> 6.0)
  - GoogleUtilities/ISASwizzler (~> 6.0)
  - GoogleUtilities/MethodSwizzler (~> 6.0)
  - GTMSessionFetcher/Core (~> 1.1)
  - Protobuf (~> 3.5)
- FirebaseRemoteConfig (4.1.0):
  - FirebaseABTesting (~> 3.0)
  - FirebaseCore (~> 6.0)
  - FirebaseInstanceID (~> 4.2)
  - GoogleUtilities/Environment (~> 6.0)
  - "GoogleUtilities/NSData+zlib (~> 6.0)"
  - Protobuf (~> 3.5)
- GoogleAppMeasurement (6.0.2):
  - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
  - GoogleUtilities/MethodSwizzler (~> 6.0)
  - GoogleUtilities/Network (~> 6.0)
  - "GoogleUtilities/NSData+zlib (~> 6.0)"
  - nanopb (~> 0.3)
- GoogleToolboxForMac/Defines (2.2.1)
- GoogleToolboxForMac/Logger (2.2.1):
  - GoogleToolboxForMac/Defines (= 2.2.1)
- "GoogleToolboxForMac/NSData+zlib (2.2.1)":
  - GoogleToolboxForMac/Defines (= 2.2.1)
- GoogleUtilities/AppDelegateSwizzler (6.2.3):
  - GoogleUtilities/Environment
  - GoogleUtilities/Logger
  - GoogleUtilities/Network
- GoogleUtilities/Environment (6.2.3)
- GoogleUtilities/ISASwizzler (6.2.3)
- GoogleUtilities/Logger (6.2.3):
  - GoogleUtilities/Environment
- GoogleUtilities/MethodSwizzler (6.2.3):
  - GoogleUtilities/Logger
- GoogleUtilities/Network (6.2.3):
  - GoogleUtilities/Logger
  - "GoogleUtilities/NSData+zlib"
  - GoogleUtilities/Reachability
- "GoogleUtilities/NSData+zlib (6.2.3)"
- GoogleUtilities/Reachability (6.2.3):
  - GoogleUtilities/Logger
- GoogleUtilities/UserDefaults (6.2.3):
  - GoogleUtilities/Logger
- GTMSessionFetcher/Core (1.2.2)
- nanopb (0.3.901):
  - nanopb/decode (= 0.3.901)
  - nanopb/encode (= 0.3.901)
- nanopb/decode (0.3.901)
- nanopb/encode (0.3.901)
- Protobuf (3.9.0)
```
Is there something I can do to make it works?
Do you know if we still can publish the app or it will be refused? 
I tried with the latest version too (6.0.6) but no luck. 

Thanks for you work

**Comment by dpa99c** [comment] 2019-08-16 07:35
Oops, this is due to an oversight by me.
When I removed the dependency on `cordova-plugin-cocoapod-supportx` to resolve #22, that removed the functionality which adds the code block to the Podspec to strip debug symbols.
So basically the `IOS_STRIP_DEBUG` plugin variable currently does nothing in recent versions of this plugin.
The best solution is if I port across the code that adds it to the Podspec into the hook scripts of this plugin so `IOS_STRIP_DEBUG` will start working again.

**Comment by dpa99c** [comment] 2019-08-16 08:03
I've published the fix for this in v6.0.7
Please regression test and let me know if you still have issues with that version.

**Closed** 2019-08-16 08:02 UTC
Labels: bug, build issue, ios

**Comment by JumBay** [comment] 2019-08-27 18:38
For me, it works with this version, but sometimes when I do a clean install (removing plugins, platform, and node_modules), I need to remove and install this plugin at the end to make it works.

**Comment by jsitu** [comment] 2019-10-22 12:19
@dpa99c I am using 6.1.0 but I am getting these as well:
>ITMS-90381: Too many symbol files - These symbols have no corresponding slice in any binary [3ACF1C6B-89CD-3AFC-A6E6-5851826B2F1D.symbols, 4FCF14BD-F72F-301D-B87F-0D799E5B44B9.symbols, 6B9E6C93-6F41-3E89-AAD0-9CE3239C1138.symbols, D9AC5CAA-FCE6-30D0-81BF-EEFC118646B7.symbols, FF90E0A6-15E2-3B51-9BE3-07A9AB6CEA3C.symbols].

**Comment by jpduckwo** [comment] 2020-06-25 05:21
This issue is back for me with v9.1.1 & v9.1.2

```
ITMS-90381: Too many symbol files - These symbols have no corresponding slice in any binary [F7A3D24C-0053-356A-925F-23FCCEF501B8.symbols, C8AB4DDC-DA83-3864-8727-0000AD058D38.symbols, 0DBE7F20-71F5-34BB-BA31-1C10A7043860.symbols, B55B0AA4-F4D5-3FC9-BD29-2C02DA4CDBB6.symbols, C59522FA-0221-3343-A076-24A5FAC42FFE.symbols, 029BD029-F164-3B7E-919C-B4DEE01AC9BF.symbols, B185E998-AA6D-3C7E-A85C-AB946C18B0BE.symbols, BA72F66F-E462-3539-9228-AC2E056F780E.symbols, 9E0D58C4-D873-3361-B585-E3EFAC2F9A51.symbols, C6D937EC-46C8-3D3F-A123-26374459270C.symbols, 518BF45A-5050-38F7-9496-13B6A0CC05DF.symbols, 347BC345-29AD-3C30-945C-3694D1915858.symbols, 39584FAB-2582-39B3-A4EA-293905D0817C.symbols].
```

I have "IOS_STRIP_DEBUG": "true" and have tried rebuilding the cordova platforms from scratch - has happened for the last two versions for me.

Any ideas?

**Comment by dpa99c** [comment] 2020-06-26 08:00
@jpduckwo [If `IOS_STRIP_DEBUG` is set to `true`](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/scripts/after_prepare.js#L155) then the plugin [injects the appropriate build setting into the `Podfile`](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/scripts/ios/helper.js#L177).

You can check if this was successful by checking `platforms/ios/Podfile` - it should contain this:

	post_install do |installer|
	    installer.pods_project.targets.each do |target|
	        target.build_configurations.each do |config|
	            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
	        end
	    end
	end

For me this is working fine on iOS use v9 of the plugin when tested with the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test).

**Comment by globules-io** [comment] 2020-07-16 16:21
Issue seems to be back with 10.1.2
Can anyone confirm? I have IOS_STRIP_DEBUG set to true and happening after upgrading from 10.0.1 to 10.1.2.
