### ISSUE TITLE
Broken compatibility with custom url scheme plugin window.handleOpenURL method

### ISSUE THREAD

**Issue by marcoNoeFi** [dpa99c/cordova-plugin-firebasex#718] opened 2022-03-02 17:38 UTC
# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)
- [X] I confirm this is a suspected bug or issue that will affect other users
- [X] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.
- [X] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.
- [X] I have checked that no similar issues (open or closed) already exist.
Yes, it seems to be  a  https://github.com/dpa99c/cordova-plugin-firebasex/issues/328 regression

**Current behavior:**
Broken compatibility with https://github.com/EddyVerbruggen/Custom-URL-scheme (tried installing both latest version 5.0.2 and from github msater branch)
With plugin version 14.0.0 the function window.handleOpenURL is not called when opening the app through a registered custom url scheme on iOS
The same code works with plugin version 13.0.1

**Expected behavior:**
function window.handleOpenURL should be called when opening through a registered custom url scheme

**Steps to reproduce:**
1) Install version 14.0.0 in combination with https://github.com/EddyVerbruggen/Custom-URL-scheme
2) Declare window.handleOpenURL as described in the other plugin README.md
3) Verify that window.handleOpenURL is never called.
4) Install previous version 13.0.1 and verify that window.handleOpenURL is called.

**Screenshots**
N/A

**Environment information**
- Cordova CLI version 
	tested with 10.0.0 and 11.0.0
- Cordova platform version
	ios 6.0.2
- Plugins & versions installed in project (including this plugin)
    
- Dev machine OS and version, e.g.
    OSX 12.2.1
        
_Runtime issue_
- Device details
   iPhone13 emulator, iPhone 8 plus emulator, iPhone 8 real device, iPhoneX real device
- OS details
   iOS 15.0 / iOS 15.3.1

_iOS build issue:_
- Node JS version
    v12.18.2
- XCode version
    13.1

**Comment by DavidStrausz** [comment] 2022-03-25 12:39
@dpa99c  The problem seems to be the GoogleSignin v6 update and in particular the following addition:

https://github.com/dpa99c/cordova-plugin-firebasex/commit/f84fe16cf219fdf1a0dd06603b628be5546ffffe#diff-f722b2da065ecdbafd682e0ecd4bde102436b45638678ac1505604e796d3cb76R291

Probably it can just be removed and the override from #328 will handle the url correctly.

**Comment by JonSmart** [comment] 2022-04-12 12:59
We have this issue, impacting another SDK that requires which also relies on access to application openUrl.  v13 works.

I can confirm that removing the block of code referenced by David above does indeed correct the issue, however I am not sure if this will cause the GID to fail - it does appear to have a fallback https://github.com/dpa99c/cordova-plugin-firebasex/compare/13.0.1-cli...14.0.0-cli#diff-aabfc02452b99b2b0599b43d56d206ac7302aa58201bdbeb855984067baf4682R154

Which also gets called if the first block of code is removed.

**Comment by dpa99c** [comment] 2022-05-16 19:49
I'll make some time this week to test and merge this and address some of the outstanding issues. Sorry I don't use this plugin much anymore but I appreciate that others do so I'll try to get a release out by the end of the week

**Comment by jpike88** [comment] 2022-05-18 15:18
@dpa99c much appreciated, keenly awaiting release :)

**Comment by PetePrattis** [comment] 2022-06-02 15:07
@dpa99c  @jpike88 The PR https://github.com/dpa99c/cordova-plugin-firebasex/pull/731 was merged, but for v14.1.0 the conflicting code is still present https://github.com/dpa99c/cordova-plugin-firebasex/blob/2b56f9211c2bbec38849310d060e802334d5173b/src/ios/AppDelegate%2BFirebasePlugin.m#L291

**Comment by jpike88** [comment] 2022-06-02 17:08
sorry I've moved onto a combo of https://github.com/onesignal/OneSignal-Cordova-SDK and https://github.com/russmedia-digital/cordova-plugin-google-signin.

This lib has been great but the Google JS sdk/firebase team have been a major letdown, I've decided to just ditch firebase altogether because of poor 1st party Cordova support

**Closed** 2022-08-01 10:36 UTC

**Comment by dpa99c** [comment] 2022-08-01 10:44
Bugfix to resolve the merge error that erroneously re-introduced the `openURL` delegate has been published to npm in `cordova-plugin-firebasex@14.2.1`
