### ISSUE TITLE
ITMS-90078: Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by yoprogramo** [dpa99c/cordova-plugin-firebasex#180] opened 2019-10-11 09:53 UTC
Every time I compile the ios app I have to change manually the entitlements to add the Push notification entitlement. There are some way to do it through the plugin?

**Comment by pghoratiu** [comment] 2019-10-11 15:47
This is working correctly, what is the problem is that other plugins are not behaving nicely overwriting these settings.
In my case it was **cordova-plugin-googleplus** which was installing the entitlements via a hook, I createad a PR for that particular problem here:
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/652

I suggest you look into the plugins folder and search for other plugins that are messing around with entitlements configuration (search for _entitlement_ keyword). 

For cordova-plugin-firebasex this is the configuration used:
https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L100

**Comment by dpa99c** [comment] 2019-10-22 16:52
As @pghoratiu suggests, this issue is caused by conflicts with other plugins.
In isolation, the entitlements management of this plugin works correctly.
Closing as there is no solution this plugin can implement that will prevent other plugins interfering with its entitlement settings.

**Closed by dpa99c** 2019-10-22 16:52 UTC
