### ISSUE TITLE
Installation of cordova-plugin-googleplus fails due to new Cocoapods Spec Url

### ISSUE THREAD

**Issue by hoi4** [dpa99c/cordova-plugin-firebasex#269] opened 2020-01-10 10:37 UTC
When using this plugin with the latest version of `cordova-plugin-googleplus`, the installation of googleplus fails with lots of warnings of the following kind:

```
[!] Found multiple specifications for `GoogleUtilities (6.1.0)`:
- /Users/xyz/.cocoapods/repos/cocoapods-/Specs/0/8/4/GoogleUtilities/6.1.0/GoogleUtilities.podspec.json
- /Users/xyz/.cocoapods/repos/master/Specs/0/8/4/GoogleUtilities/6.1.0/GoogleUtilities.podspec.json
```

My Podfile:
```
source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!
target 'MyApp' do
	project 'MyApp.xcodeproj'
	pod 'Firebase/Core', '6.11.0'
	pod 'Firebase/Auth', '6.11.0'
	pod 'Firebase/Messaging', '6.11.0'
	pod 'Firebase/Performance', '6.11.0'
	pod 'Firebase/RemoteConfig', '6.11.0'
	pod 'Fabric', '1.10.2'
	pod 'Crashlytics', '3.14.0'
	pod 'GoogleSignIn', '~> 4.4.0'
	pod 'GoogleUtilities', '~> 6.3.0'
end
```

`cordova-plugin-googleplus` uses the old Cocoapods Spec Url which leads to the two sources in the Podfile.

When reverting the url change in #173, both plugins successfully install.

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `Installed platforms:  android 8.1.0  ios 5.1.1`
- Node version: `v10.18.0`
- Cocoapods Version: 1.7.5

**Comment by dpa99c** [comment] 2020-01-10 13:02
This is because `cordova-plugin-googleplus` [still uses the old URL](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/blob/master/plugin.xml#L107) hence it will need updating also to use the new URL as specified in #173.

I suggest opening an issue/PR against `cordova-plugin-googleplus` or forking it and updating it yourself.

Closing as this plugin is not the cause of the issue.

**Closed by dpa99c** 2020-01-10 13:02 UTC
Labels: ios, support

**Comment by mohamedsharaf** [comment] 2020-01-20 00:02
update google sign plugin.xml 
pod section to this works

` 
    <podspec>
      <config>
        <source url="https://cdn.cocoapods.org/"/>
      </config>
      <pods use-frameworks="true">
        <pod name="GoogleSignIn" spec="~> 4.4.0"/>
        <pod name="GoogleUtilities" spec="~> 6.5.0"/>
      </pods>
    </podspec>`
