### ISSUE TITLE
error: no suitable method found for success(boolean)

### ISSUE THREAD

**Issue by AmitKKhanchandani** [dpa99c/cordova-plugin-firebasex#83] opened 2019-08-12 07:46 UTC
Hi @dpa99c 

![image](https://user-images.githubusercontent.com/11069057/62851279-37c94680-bd03-11e9-8a10-b6dc4d50c8a1.png)

How can i resolve this issue?

`\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:406: error: no suitable method found for success(boolean)
                    callbackContext.success(areNotificationsEnabled);
                                   ^
    method CallbackContext.success(JSONObject) is not applicable
      (argument mismatch; boolean cannot be converted to JSONObject)
    method CallbackContext.success(String) is not applicable
      (argument mismatch; boolean cannot be converted to String)
    method CallbackContext.success(JSONArray) is not applicable
      (argument mismatch; boolean cannot be converted to JSONArray)
    method CallbackContext.success(byte[]) is not applicable
      (argument mismatch; boolean cannot be converted to byte[])
    method CallbackContext.success(int) is not applicable
      (argument mismatch; boolean cannot be converted to int)
Note: Some input files use or override a deprecated API.`

Some Background about the error.

I Migrated from cordova-plugin-firebase, as mentioned in the readme guide
I followed this guide

rm -Rf platforms/android
cordova plugin rm cordova-plugin-firebase
rm -Rf plugins/ node_modules/
npm install
cordova plugin add cordova-plugin-firebasex
cordova platform add android

**Comment by dpa99c** [comment] 2019-08-12 07:58
Sorry this was caused by my fix to #81. Will push out a patch release to fix it.

**Comment by dpa99c** [comment] 2019-08-12 07:59
Fixed in v6.0.6

**Closed** 2019-08-12 07:59 UTC

**Comment by Roman8817** [comment] 2019-08-15 09:12
Hello.
Now I am use Cordova-plugin-firebasex 6.0.6 in ionic 4 app. I tried to use that plugin for push notification. But it is not working. Any comment for me please?
I used Cordova-ios@5.0.0. And I used Cordova-plugins-googlemaps and Cordova-plugin-geolocation plugins using google services.
Please help me.

**Comment by dpa99c** [comment] 2019-08-15 09:16
@Roman8817 Please use (build and run) the [example project](https://github.com/dpa99c/cordova-plugin-firebasex) as a working reference.
Specifically for Ionic 4, see https://github.com/ionic-team/ionic-native/pull/3106
