### ISSUE TITLE
Background notification not received

### ISSUE THREAD

**Issue by Punit-Vajpeyi** [dpa99c/cordova-plugin-firebasex#42] opened 2019-07-15 14:15 UTC
I have integrated the plugin for Android and able to receive the notification in foreground, but background notification is not working.

Application configuration:

Ionic:

   Ionic CLI          : 5.0.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 10 other plugins)

Utility:

   cordova-res : 0.4.0
   native-run  : 0.2.6

System:

   ios-deploy : 1.9.2
   NodeJS     : v10.16.0 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

**Comment by dpa99c** [comment] 2019-07-16 13:42
I've just published `cordova-plugin-firebasex@5.0.0`.
This is a major version that reworks the cloud messaging code and so will resolve this issue.
Please regression test using v5.0.0 of this plugin to confirm.

Note: v5.0.0 makes breaking changes to the plugin API - see the [CHANGELOG](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/CHANGELOG.md#version-500) for details.

You may find it useful to test using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) which has a built-in FCM messaging client with test messages.

**Comment by dpa99c** [comment] 2019-07-17 15:47
Fixed in v5.0.0

**Closed by dpa99c** 2019-07-17 15:47 UTC
Labels: awaiting response, bug, legacy

**Comment by frebe73** [comment] 2019-07-18 18:48
I am using version 5.0.0 of this plugin but this still seem to be a problem. Notifications works fine when the app is running in foreground or can be found among recents apps. But when I close the application on my phone (Asus Zenphone 5), notifications are not longer received. I have installed my Cordova app on my phone using APK. Will it be different if I install the app from Google Play?

**Comment by dpa99c** [comment] 2019-07-18 18:59
Please try building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) (you may need to change the package ID so you can receive push notifications on iOS). 
I can confirm background notifications (received when the app is not running) are working on Pixel 2 XL running Android Q Beta 5, Pixel 2 running Android 9.0 and Samsung Galaxy S6 running Android 7.0

FYI I've just published v6.0.0 which further rationalises push notifications behaviour between platforms.

**Comment by molinet88** [comment] 2019-12-04 09:50
Background notifications are not working on iOS (plugin v6.1.0).
I tried the ionic example project and the alert shows when the app is in foreground, but when is in background no banner is shown and the alert appears when I open the app.
I'm expecting to see a banner when the app is closed.

ionic@3.20.1
cordova@9.0.0
cordova-ios@5.1.1
Tested on iOS 13.2

**Comment by kelpie278** [comment] 2019-12-04 09:56
@molinet88 , just checking, do you have a apple developer account and set up the certificates in firebase?

**Comment by molinet88** [comment] 2019-12-04 10:01
Sure, if I was not I wasn't receiving the notification when app is in foreground.

**Comment by molinet88** [comment] 2019-12-05 11:58
@dpa99c any updates on this? I'm stuck with this issue... I don't understand why banner is not showing when app is closed or background (app notification permissions are enabled).

**Comment by dpa99c** [comment] 2019-12-05 12:19
@molinet88 If the "ionic example project" you tested with is [cordova-plugin-firebasex-ionic3-test](https://github.com/dpa99c/cordova-plugin-firebasex-ionic3-test), that is not a complete test project but simply an illustration of how to use the plugin API with Ionic 3.

Please use the full [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to test plugin functionality - be sure to follow the setup instructions in that project.

**Comment by molinet88** [comment] 2019-12-05 12:24
Ok, I'll give it a try and send you a feedback.
Thank you!

**Comment by molinet88** [comment] 2019-12-12 08:08
@dpa99c I tried the full [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test), following all instructions (package id, firebase project, GoogleService-Info.plist...).
When I send a test message using `npm run-script send` the console outputs an error:

`Error: Requested entity was not found.`

I think this means that the device is not registered, but I don't get why. Remote notifications permission is granted and the token I use is the logged in the app console.

Any ideas? Please help.

**Comment by dpa99c** [comment] 2019-12-12 08:33
Be sure to use the FCM token not the APNS token

**Comment by molinet88** [comment] 2019-12-12 08:40
> Be sure to use the FCM token not the APNS token

I'm using the FCM token

**Comment by dpa99c** [comment] 2019-12-12 09:16
Not sure then - works fine for me (and other devs here)

**Comment by molinet88** [comment] 2019-12-12 10:27
It works on Android devices, but not on iPhones. I'm using an iPhone 7 Plus with iOS 13.2.3.
@dpa99c can you confirm that it works on these devices?

**Comment by dpa99c** [comment] 2019-12-12 10:42
@molinet88 yes works fine for me on iPhone 7 and iPhone X physical devices - I would suspect your APNS setup is the issue.

**Comment by sprengerst** [comment] 2020-01-04 16:40
Is there a guide for APNS Setup, it seems that there are various ways out there? I tried it with Dev/Prod Key and the global key variant, but no luck here too. :-/

**Comment by zulkarnainshah** [comment] 2020-02-13 18:27
The notifications are received in background mode just fine. I logged outputs in console and checked them in XCode. But the problem is that they are not showing up in the system tray in iOS. On Android though when I am in background mode, the notifications are delivered in notifications area which can be seen with swipe down. But on iOS when i am in background mode, the notifications are not showing up in the system tray, but they are received just fine when I open the app and see my console logs. Any idea why they are not showing up in the system tray in iOS ? @dpa99c

**Comment by dpa99c** [comment] 2020-02-13 18:58
@zulkarnainshah most likely something wrong with your APNS configuration.
Make sure you have setup APNS in the Firebase Console for your app and that the app ID has the correct settings for the provisioning profile in the Apple Member Centre.

**Comment by sprengerst** [comment] 2020-02-13 19:09
@zulkarnainshah it only works on real iphone not emulator. You have to correctly set up apns with the firebase console, it works with the link of the firebasex guide here. Also be sure that your iphone has a sim card, otherwise it won't receive an apns token. You can test by logging "getApnsToken", I think in your case it returns null. So Apns is not configured.

**Comment by zulkarnainshah** [comment] 2020-10-26 09:47
Yeah, @sprengerst . I had not done that step and that was the only issue. Thanks a lot.
