### ISSUE TITLE
fetchFirestoreCollection returning Collection not found iOS

### ISSUE THREAD

**Issue by devstevehowe** [dpa99c/cordova-plugin-firebasex#606] opened 2021-03-26 01:39 UTC
Running app using ionic capacitor run ios -l --external

Code:

import { FirebaseX } from "@ionic-native/firebase-x";

const fetchHome = async() => {
        // @ts-ignore
        await FirebaseX.fetchFirestoreCollection('home', '', function(documents){
            console.log("Successfully fetched collection: "+JSON.stringify(documents));
        });
    }

Receiving the following in iOS log:

[error] - FirebasePlugin[native]: Collection not found

Can verify that the system is connecting to my Firebase through the following:

const userID = FirebasePlugin.getCurrentUser(function(user) {
    setUserDetails(user.uid);
    setUserNamed(user.email);
  }, function(error: string) {
    console.error("Failed to get current user data: " + error);
  });

userDetails is displaying the appropriate uid. 

I have verified that "home" is the correct collection. I expect that I would receive the appropriate response back as I know the system has the data, and firebasex and iOS have the correct plist details.

**Comment by dpa99c** [comment] 2021-03-26 08:17
I regression tested all plugin functionality on both platforms with the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as part of the v12 major release and found no regression issues.

Specifically I just retested Firestore functionality on iOS and it appears to work as expected: 
<img src="https://user-images.githubusercontent.com/2345062/112602323-6b3ee300-8e0b-11eb-9f46-7aa18750b42a.png" width="400" />

Therefore I'm closing this on the basis that the issue is specific to your configuration.
However if you can provide evidence that this is a more generic issue with the plugin affecting other users, I'll be happy to reopen and investigate.

**Closed by dpa99c** 2021-03-26 08:17 UTC
