### ISSUE TITLE
iOS Foreground Notifications not working

### ISSUE THREAD

**Issue by maximilianloy** [dpa99c/cordova-plugin-firebasex#364] opened 2020-04-12 16:32 UTC
# Bug report

**Current behavior:**

Foreground notifications do not work on iOS. onMessageReceived() is not executed, instead an exception is printed on the console. 
Same code was working previously, after upgrading dependencies this issue showed up.

If the app is in the background, the push notification arrives.
On Android both foreground and background work.

**Expected behavior:**

onMessageReceived() should be executed

**Steps to reproduce:**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
`9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `cordova platform ls`
```
Installed platforms:
  android 8.1.0
  ios 5.1.1
Available platforms: 
  browser ^6.0.0
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0
```

- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
```
com.googlemaps.ios 3.8.0 "Google Maps SDK for iOS"
cordova-plugin-advanced-http 2.4.1 "Advanced HTTP plugin"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-customurlscheme 5.0.1 "Custom URL scheme"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 9.0.2-cli "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-safariviewcontroller 1.6.0 "SafariViewController"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-inject-cookie 1.0.2 "WKWebViewInjectCookie"
cordova-plugin-x-socialsharing 5.6.4 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"
sentry-cordova 0.17.0 "Sentry"
```
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
```
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G3020
```
        
_Runtime issue_
- Device details
    - multiple devices running iOS 13.4 and 12.4

- XCode version
`11.3.1`

**Related code:**
```
constructor( private firebase: FirebaseX, ..) {}

this.firebase.onMessageReceived().subscribe(data => {
  console.log('NOTIFCATION RECEIVED');
```

**Console output**
<details>
<summary>console output</summary>

```
-[NSTaggedPointerString isEqualToNumber:]: unrecognized selector sent to instance 0xb9b397627709a584
FirebasePlugin[native] ERROR: EXCEPTION: -[NSTaggedPointerString isEqualToNumber:]: unrecognized selector sent to instance 0xb9b397627709a584
ERROR: FirebasePlugin[native]: EXCEPTION: -[NSTaggedPointerString isEqualToNumber:]: unrecognized selector sent to instance 0xb9b397627709a584
ERROR: FirebasePlugin[native]: EXCEPTION: -[NSTaggedPointerString isEqualToNumber:]: unrecognized selector sent to instance 0xb9b397627709a584
```

</details><br/><br/>

**Other information:**

- https://github.com/dpa99c/cordova-plugin-firebasex/issues/224
- https://github.com/firebase/firebase-js-sdk/issues/2610

**Comment by dpa99c** [comment] 2020-04-13 08:01
I suspect this is being caused by a specific value in the notification message payload, which is parsed by the plugin in order to display a foreground notification.

Please try the following:
- Build & run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) app (as it's a known codebase)
- Use its [built-in FCM messaging client](https://github.com/dpa99c/cordova-plugin-firebasex-test#messaging-client) to send some of the [canned test messages](https://github.com/dpa99c/cordova-plugin-firebasex-test/tree/master/messages) to confirm they work OK
- Send the FCM message that caused the above issue and confirm if the issue occurs
- If so, please provide the payload of that FCM message (feel free to redact/scramble any sensitive values) so I can determine which value is causing the issue

**Comment by maximilianloy** [comment] 2020-04-13 15:42
Thanks for the hint Dave!

It's indeed related to the content - I get the error when I send a message including data:
```
{
  "registration_ids": [
    "..."
  ],
  "notification": {
    "notId": 1,
    "title": "notification title",
    "body": "notification body",
    "color": "#F53D3D",
    "icon": "ic_stat_action_announcement",
    "sound": "alarma.wav",
    "android_channel_id": "alarm"
  },
  "collapse_key": "collapse_key_1",
  "priority": "high",
  "content_available": true,
  "data": {
    "somedata": "asdf"
  }
}
```

Sending without "content_available": true and "data" is working

**Comment by dpa99c** [comment] 2020-04-13 17:41
The problem is that the message payload you are sending is invalid. If I try to send that using the FCM client in the test project, the Firebase Admin SDK fails with this:

    ERROR: Error: Invalid JSON payload received. Unknown name "notId" at 'message.notification': Cannot find field.
    Invalid JSON payload received. Unknown name "color" at 'message.notification': Cannot find field.
    Invalid JSON payload received. Unknown name "icon" at 'message.notification': Cannot find field.
    Invalid JSON payload received. Unknown name "sound" at 'message.notification': Cannot find field.
    Invalid JSON payload received. Unknown name "android_channel_id" at 'message.notification': Cannot find field.
    Invalid JSON payload received. Unknown name "collapse_key" at 'message': Cannot find field.
    Invalid JSON payload received. Unknown name "priority" at 'message': Cannot find field.
    Invalid JSON payload received. Unknown name "content_available" at 'message': Cannot find field.

The plugin currently expects a valid payload which conforms to the FCM specification so in this case it is failing ungracefully.

If I fix your structure to conform to the nearest approximation which is a valid FCM payload structure, it works correctly:

```json
{
  "name": "1",
  "notification": {
    "title": "notification title",
    "body": "notification body"
  },
  "android":{
    "collapse_key": "collapse_key_1",
    "priority": "high",
    "notification": {
      "channel_id": "alarm",
      "icon": "ic_stat_action_announcement",
      "color": "#F53D3D"
    }
  },
  "apns": {
    "payload": {
      "aps": {
        "content-available": 1
      }
    }
  },
  "data": {
    "notification_foreground": "true",
    "somedata": "asdf"
  }
}
```

So while it's true that the plugin could more gracefully handle the error by validating the received data structure before attempting to parse it, it's also fair that the plugin should be able to assume that the structure it receives is a valid payload conforming to the FCM specification.

For this reason I'm closing this issue, although payload validation is a nice-to-have feature which is why I'll create a separate issue to capture it in the backlog.

**Closed by dpa99c** 2020-04-13 17:41 UTC
Labels: ios, more info needed, runtime issue

**Comment by maximilianloy** [comment] 2020-04-13 20:37
Great, I fixed it and now both Android and iOS work with foreground notifications.

But the sound stopped working for background notifications on Android 9. The channel is created from the app (it was working before with the other payload).

This is how the payload looks like (tried many variations I found in the docs):
```
{
    name: "1",
    registration_ids: tokens,
    notification: {
      title,
      body,
      sound: 'alarma.wav'
    },
    android: {
      collapse_key: deviceId,
      priority: 'high',
      notification: {
        channel_id: 'alarm',
        sound: 'alarma.wav',
        icon: 'ic_stat_action_announcement'
      }
    },
    apns: {
      payload: {
        aps: {
          sound: 'alarma.wav',
          'content-available': 1
        }
      }
    },
    data: {
      notification_foreground: 'true',
      notification_android_channel_id: 'alarm',
      notification_android_sound: 'alarma.wav',
      ...data
    }
  }
```
By the way I am using a POST to https://fcm.googleapis.com/fcm/send to send the push.

Thanks for your help Dave! Donation is coming...

**Comment by dpa99c** [comment] 2020-04-14 06:49
AFAIK `notification_android_sound` should not include the file type suffix, i.e.:

    notification_android_sound: 'alarma',

For example [this test message](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/android_data_notification_custom_channel.json#L12) refers to [this sound file](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/res/android/raw/blackberry.mp3)

**Comment by maximilianloy** [comment] 2020-04-14 08:53
I found the solution for me now. Just had to remove `"content_available": true` from my original payload and everything is working now as expected on both platforms both in foreground and background.

**Comment by dcxn** [comment] 2020-09-11 11:02
> I found the solution for me now. Just had to remove "content_available": true from my original payload

Hey guys, allow me to unearth this issue because we are also experiencing it. What I think happened is that Maximilianloy was using a payload that was valid for the [FCM legacy HTTP API](https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json). 

> The problem is that the message payload you are sending is invalid.

So, it's not invalid, the issue is that plugin doesn't seem to support the legacy api valid payloads, eg. the **content_available** field. We have the same issue, the backend that sends messages is still using this legacy api. And legacy api has no EOL afaik, which makes it difficult to argue for migration with the people that control such backends. Any possibility that the plugin could support legacy api correctly Dave?

**Comment by dpa99c** [comment] 2020-09-11 11:10
I have no plan to add support for the legacy API as it's likely Google will deprecate it at some unknown point in the future in favour of the new v1 API and it would be quite a lot of work to adapt the plugin to work with both the legacy and new v1 APIs on both Android & iOS platforms.

However, if someone was to create a PR which did so and which was proven to work with both APIs (the example project would also require a PR which added support for a legacy API client with which to validate the implementation as well as legacy API versions of the test messages), then I would consider merging it into plugin.

**Comment by dcxn** [comment] 2020-09-11 11:54
That is very reasonable. Thanks a lot for the quick answer.

**Comment by theavijitsarkar** [comment] 2021-01-12 13:44
Hi @dpa99c 
Thank you for this awesome plugin. Everything works well. I am able to send data notifications to my ios app, however when app is in background it hits onMessageReceived, but when in foreground it does not hit the onMessageReceived

**My Server Code**
 ```
var payload = {
        name: "call_notification",
        token: token.toString(),
        notification: {
          title: "New Notification",
          body: `XXX for ${data.name || data.phone}`,
        },
        data: {
          notification_foreground: "true",
          action: action.toString(),
          contact: JSON.stringify(data),
        },
        webpush: {
          headers: {
            Urgency: "high",
          },
        },
        android: {
          notification: {
            sound: "default",
          },
        },
        apns: {
          payload: {
            aps: {
              sound: "default",
              "content-available": 1,
            },
          },
        },
      };

      await admin.messaging().send(payload);

```
**My iOS Console from Web Debug**
 
![Screenshot 2021-01-12 at 7 13 39 PM](https://user-images.githubusercontent.com/8898721/104322007-5d670a80-550a-11eb-82d1-3e569d5a39c7.png)



**My JS code**
This does not get called
` window.FirebasePlugin.onMessageReceived(console.log, function(error) {
            console.error(error);
          });
`

**When App is in background**
![Screenshot 2021-01-12 at 7 13 21 PM](https://user-images.githubusercontent.com/8898721/104321921-432d2c80-550a-11eb-92a6-aac424b91764.png)

**Comment by ken1106** [comment] 2021-03-17 10:09
> Hi @dpa99c
> Thank you for this awesome plugin. Everything works well. I am able to send data notifications to my ios app, however when app is in background it hits onMessageReceived, but when in foreground it does not hit the onMessageReceived
> 
> **My Server Code**
> 
> ```
> var payload = {
>        name: "call_notification",
>        token: token.toString(),
>        notification: {
>          title: "New Notification",
>          body: `XXX for ${data.name || data.phone}`,
>        },
>        data: {
>          notification_foreground: "true",
>          action: action.toString(),
>          contact: JSON.stringify(data),
>        },
>        webpush: {
>          headers: {
>            Urgency: "high",
>          },
>        },
>        android: {
>          notification: {
>            sound: "default",
>          },
>        },
>        apns: {
>          payload: {
>            aps: {
>              sound: "default",
>              "content-available": 1,
>            },
>          },
>        },
>      };
> 
>      await admin.messaging().send(payload);
> ```
> 
> **My iOS Console from Web Debug**
> 
> ![Screenshot 2021-01-12 at 7 13 39 PM](https://user-images.githubusercontent.com/8898721/104322007-5d670a80-550a-11eb-82d1-3e569d5a39c7.png)
> 
> **My JS code**
> This does not get called
> `window.FirebasePlugin.onMessageReceived(console.log, function(error) { console.error(error); });`
> 
> **When App is in background**
> ![Screenshot 2021-01-12 at 7 13 21 PM](https://user-images.githubusercontent.com/8898721/104321921-432d2c80-550a-11eb-92a6-aac424b91764.png)

You can try remove `"content-available": 1`

**Comment by markterrill** [comment] 2021-05-12 04:40
I got here via a different path worth noting (and putting into google search). If you're using Google Firebase cloud functions you would be sending notifications via ```admin.messaging().sendToDevice(tokensiOS, msgiOS, options)...``
The key bit there is the options argument, which corresponds to: https://firebase.google.com/docs/reference/admin/node/admin.messaging.MessagingOptions

It includes 'contentAvailable' as an option that is fed into the legacy API (if you're using that).

Simple tested resolution that removes the NSTaggedPointerString error when receiving messages in foreground is to simply remove the contentAvailable element of the options argument.
