### ISSUE TITLE
build error after updating to latest version in ionic5 app

### ISSUE THREAD

**Issue by bhargavas12** [dpa99c/cordova-plugin-firebasex#642] opened 2021-07-20 12:56 UTC
**Updated the plugin version to 13.0.0 in ionic 5 app.**
**Build failed with the below error:**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
28 actionable tasks: 3 executed, 25 up-to-date
org.apache.cordova:CordovaLiborg.apache.cordova:CordovaLibCommand failed with exit code 1: C:\test\new ionic v4\ionic-v4\platforms\android\gradlew cdvBuildDebug -b C:\test\new ionic v4\ionic-v4\platforms\android\build.gradle
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd build android exited with exit code 1.

**And my build.gradle file contains this:**

buildscript {
    ext.kotlin_version = '1.3.50'
    apply from: 'repositories.gradle'
    repositories repos

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    apply from: 'repositories.gradle'
    repositories repos

    //This replaces project.properties w.r.t. build settings
    project.ext {
      defaultBuildToolsVersion="29.0.2" //String
      defaultMinSdkVersion=22 //Integer - Minimum requirement is Android 5.1
      defaultTargetSdkVersion=29 //Integer - We ALWAYS target the latest by default
      defaultCompileSdkVersion=29 //Integer - We ALWAYS compile with the latest by default
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by dpa99c** [comment] 2021-07-20 21:43
Please build the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) which is a known working codebase to verify your local build environment.

If this builds successfully, check you don't have old versions of the Firebase SDK components pinned as this plugin's variables in your `package.json` or `plugins/fetch.json`.

**Comment by bhargavas12** [comment] 2021-07-21 07:21
cleaned everything and tried fresh install but the same error.
I have ionic setup.., Tried to build example project but its not ionic project so facing issues with that too.

**Comment by dpa99c** [comment] 2021-07-22 07:08
This is a Cordova plugin, so the example project is a Cordova project - use the example project to validate your build environment.

Closing as I believe the issue is with your build environment, not an issue with the plugin.
If you can demonstrate an issue when building the example project which is reproducible for other users, I'll be happy to reopen.

**Closed by dpa99c** 2021-07-22 07:08 UTC
Labels: android, awaiting response, build issue, ionic, support

**Comment by bhargavas12** [comment] 2021-07-22 09:53
**Sample project is built successfully.**
But in my project I have more dependencies. Take a look at below plugins that I have gradle dependencies:

**Platform/Android/App/build.gradle**

// PLUGIN GRADLE EXTENSIONS START
apply from: "../com.unarin.cordova.beacon/test-cordova-plugin-ibeacon.gradle"
apply from: "../cordova-android-support-gradle-release/test-cordova-android-support-gradle-release.gradle"
apply from: "../cordova-plugin-fingerprint-aio/test-build.gradle"
apply from: "../cordova-plugin-firebasex/test-build.gradle"
apply from: "../cordova-plugin-proguard/test-build.gradle"
apply from: "../cordova-support-google-services/test-build.gradle"
// PLUGIN GRADLE EXTENSIONS END
