### ISSUE TITLE
Android Notification Groups (Bundled Notifications)

### ISSUE THREAD

**Issue by brassier** [dpa99c/cordova-plugin-firebasex#251] opened 2019-12-09 22:17 UTC
# Feature request

**Overview:**
We have an app that has a couple different types of notifications.  It would be nice to be able to group these.  On the Android side it looks like this can be done with Notification Groups (Bundled Notifications).  Has this feature been a consideration for the FirebaseX plugin?

Thanks for the great work on this plugin!

**Links:**
https://developer.android.com/training/notify-user/group

**Comment by dpa99c** [comment] 2019-12-10 08:11
Duplicate of #46

**Closed by dpa99c** 2019-12-10 08:11 UTC
