### ISSUE TITLE
iOS - not getting remote notifications at all

### ISSUE THREAD

**Issue by Haroon6138** [dpa99c/cordova-plugin-firebasex#354] opened 2020-03-30 22:50 UTC
#Bug report

**Current behavior:**

First of all,  Thanks a lot for this awesome plugin, I am using this plugin witn Ionic 4.
I am on iPhone XS Max/iOS 13.4 and I've tried everything since last 2 days on this issue

Still no avail. To summarize:

I've Checked on multiple plugin versions i.e. 7.0.x till 9.0.1
I've checked my bundle identifier matches the one in provisioning profile/development portal
I've created a new development push APNS certificate
I've created a new development certificate
I've created a new provisioning profile for that development certificate
I've downloaded both the certificate and provisioning profile, and obviously, double clicked them to install
I've verified that everything is right on Developer Portal: all certificates and provisioning profiles valid, push enabled and configured with my new APNS certificate
I've uploaded my new APNS certificate to firebase console
I've also tried with .p8 key on firebase console
I've made sure that I'm using the correct certificate/provisioning profile pair at Xcode to codesign
I've checked Notifications settings in case my app is not allowed to receive pushes, it's not there
I've tried setting date manually to tomorrow and tried re-installing the app
I've deleted the app from my device
I've deleted any related provisioning profiles from my device
I've restarted my device multiple times
I've switched my device network to cellular from wifi & vice versa multiple times

Please Please any help would be highly appreciated

**Expected behavior:**
I should be able to receive push notifications when app is closed or in background

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Ionic Info
Ionic:
   Ionic CLI                     : 5.4.4 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 41 other plugins)

Utility:
   cordova-res : 0.8.0 (update available: 0.11.0)
   native-run  : not installed

System:
   ios-deploy : 1.9.2
   ios-sim    : 8.0.2
   NodeJS     : v11.12.0 (/usr/local/bin/node)
   npm        : 6.7.0
   OS         : macOS Catalina
   Xcode      : Xcode 11.4 Build version 11E146

- Cordova CLI version 
	- 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- ios 5.1.1
- Plugins & versions installed in project (including this plugin)
com-badrit-base64 0.2.0 "Base64"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-opentok-android-permissions 1.0.0 "Cordova Opentok/WebRTC Android Permissions"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-background-geolocation 3.1.0 "CDVBackgroundGeolocation"
cordova-plugin-background-mode 0.7.3 "BackgroundMode"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-ble-central 1.2.4 "BLE"
cordova-plugin-calendar 5.1.5 "Calendar"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.5.6 "cordova-plugin-filepath"
cordova-plugin-filepicker 1.1.6 "File Picker"
cordova-plugin-fingerprint-aio 3.0.0 "FingerprintAllInOne"
cordova-plugin-firebasex 7.0.1 "Google Firebase Plugin"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-health 1.1.3 "Cordova Health"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.3-dev "Network Information"
cordova-plugin-opentok 3.4.3 "OpenTokCordovaPlugin"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-themeablebrowser 0.2.17 "ThemeableBrowser"
cordova-plugin-voippush 0.0.1 "VoipPush"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 3.4.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-google-services 1.3.2 "cordova-support-google-services"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
phonegap-plugin-multidex 1.0.0 "Multidex"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.2 "Launch Navigator"
wifiwizard2 3.1.1 "WifiWizard2"
- Dev machine OS and version, e.g.
    - OSX
ProductName:    Mac OS X
ProductVersion: 10.15.2
BuildVersion:   19C57
 
_Runtime issue_
- Device details
    - iPhone XS Max
- OS details
    - iOS 13.4
_iOS build issue:_
- Node JS version
    - v11.12.0
- XCode version
Version 11.4 (11E146)

**Comment by dpa99c** [comment] 2020-03-31 06:47
Please re-test using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to rule out causes in 3rd party projects such as plugin conflicts. Follow the instructions exactly to ensure APNS has been set up correctly. If you do not receive background notifications on iOS using the example app, the cause is likely to be your APNS setup in Firebase.

Remote notifications functionality provided by this plugin has been regression tested in all scenarios on both platforms and is in production use in numerous apps including my own, so this is not a bug with the plugin.
Closing as I'm unable to offer free user support for issues when integrating into 3rd party codebases.

**Closed by dpa99c** 2020-03-31 06:47 UTC

**Comment by Haroon6138** [comment] 2020-03-31 13:28
@dpa99c how much will you charge for integration support into our codebase?

**Comment by dpa99c** [comment] 2020-03-31 14:19
@Haroon6138 sorry if I made it sound like I was offering paid support - I simply don't have the time right now to offer any kind of user support (paid or otherwise) as my time is fully committed at the moment.

**Comment by Haroon6138** [comment] 2020-03-31 14:20
@dpa99c right still thanks a lot for your timely responses brother.

**Comment by Haroon6138** [comment] 2020-04-01 13:32
@dpa99c the issue has been resolved, Basically it's working when i create an AdHoc build & install it on phone & check it. Basically my production aps-environment is working, Not the development, Very peculiar.
