### ISSUE TITLE
[BUG] No sound and vibration in iOS devices

### ISSUE THREAD

**Issue by kyoz** [dpa99c/cordova-plugin-firebasex#322] opened 2020-03-02 10:04 UTC
# Bug report

**Current behavior:**

Firstly i'v tried this plugin in Android and it working perfectly. 

But with iOS, when sending push notification with no sound config, 'default' or custom sound. On receiver iOS device, notifications just show on but doesn't have any sound as well as vibration.

I'v tried every thing in your document and in the internet. but not thing work :cry:
```

Like
{
  "name": "my_notification",
  "notification": {
    "body": "Notification body",
    "title": "Notification title"
  },
  "apns": {
      "payload": {
        "aps": {
          "sound": "default",
        }
      }
    }
}
```

Or if i use custom sound or anything else. They doesn't work at all.

I pretty sure cause i'm using the [cordova-plugin-firebasex-test](https://github.com/dpa99c/cordova-plugin-firebasex-test) without any changes. Just config so they can received push message on iphones.

**Expected behavior:**

When send push notification for iOS device, they must have default sound and vibration.

**Environment information**
- Cordova CLI version 
	- 9.0.0
- Cordova platform version
	- iOS: 5.1.1
        - Android: ^8.0.0
- Plugins & versions installed in project (including this plugin)
    - cordova-custom-config 5.1.0 "cordova-custom-config"
    - cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
    - cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
    - cordova-plugin-dialogs 1.3.2-dev "Notification"
    - cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
    - cordova-plugin-firebasex 8.1.0 "Google Firebase Plugin"
    - cordova-plugin-whitelist 1.3.4 "Whitelist"
- Dev machine OS and version, e.g.
    - OSX
        - `Mojava-10.14.6`
        
_Runtime issue_
- Device details
    - iPhone 5s (iOS 12)
    - iPhone 6s (iOS 13)
    - iPhone 7+ (Almost Latest iOS)
	
_iOS build issue:_
- Node JS version
    - v12.8.0
- XCode version
    - 11.3.1

**Other information:**

- I don't quite understand this but when i compose notification in *Firebase Cloud Messaging* with just `Notification title` and `Notification text`. It have no sound, no vibration.

- But when i go all the way to *Additional options (optional)* and choose `Enabled` for sound. It magically have sound and vibration. I really don't understand this.

<img width="358" alt="Screen Shot 2020-03-02 at 16 47 14" src="https://user-images.githubusercontent.com/29815830/75665598-fac89f80-5ca6-11ea-9787-3a4b2ccce9bc.png">

**Comment by dpa99c** [comment] 2020-03-02 11:21
I am unable to reproduce the issue of notification sound or vibration not working: 

See [this screen capture](http://ge.tt/8JCkXZ13) from my iPhone 7 (iOS 13.3.1) receiving the [ios_notification_custom_sound_and_badge](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/ios_notification_custom_sound_and_badge.json) test message using the [example project app](https://github.com/dpa99c/cordova-plugin-firebasex-test).

As you can hear, both the custom sound plays and the device vibrates. This works with the app in the background, foreground or not running. It also works with the [default sound](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/ios_notification_default_sound_and_badge.json).

Please try sending the example same message using the built-in FCM client in the example project and confirm your results.

However, I'm closing this as I'm satisfied the plugin is behaving correctly.

**Closed by dpa99c** 2020-03-02 11:21 UTC
