### ISSUE TITLE
[iOs] Apple signin user details on authentication doesn't contain name

### ISSUE THREAD

**Issue by chaitanya-deep** [dpa99c/cordova-plugin-firebasex#479] opened 2020-08-05 15:17 UTC
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
Edited authenticateUserWithApple function to the code mentioned below

**Expected behavior:**
The object is supposed to contain a key with `name`

**Environment information**
- Cordova CLI version 
9.0.0 (cordova-lib@9.0.1)

- Cordova platform version
ios 6.1.0

- Plugins & versions installed in project (including this plugin)
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-customfcmreceiver 1.0.0 "Custom FCM Receiver"
cordova-plugin-dialogs 1.3.2-dev "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-firebasex 10.0.0 "Google Firebase Plugin"
cordova-plugin-hello-c 1.1.1 "Hello"
cordova-plugin-whitelist 1.3.4 "Whitelist"

- Dev machine OS and version, e.g.
Mac OS X, 10.15.6
        
_Runtime issue_
- Device details
iPhone SE (2nd generation) simulator

- OS details
iOS 13.6

**Related code:**
```
function authenticateUserWithApple(){
    FirebasePlugin.authenticateUserWithApple(function(credential) {
        authCredential = credential;
        FirebasePlugin.signInWithCredential(credential, () => {
            FirebasePlugin.getCurrentUser((user) => {
                console.log(user);
            }, function () {
                console.log('Error');
            });
        }, (error) => {
            console.error("Failed to sign in", error);
        });
    }, function(error) {
        logError("Failed to authenticate with Apple", error);
    }, 'en');
}
```

**Console output**
```
2020-08-05 20:39:08.847826+0530 FirebaseTest[60749:4515213] FirebasePlugin[native]: Enter foreground: FCM direct channel = false
2020-08-05 20:39:09.676455+0530 FirebaseTest[60749:4515213] {"email":"***@gmail.com","isAnonymous":0,"idToken":"***","uid":"***","emailIsVerified":true,"providerId":"apple.com"}
2020-08-05 20:44:06.225969+0530 FirebaseTest[60749:4515213] FirebasePlugin[native] LOG: Enter background: FCM direct channel = false
2020-08-05 20:44:06.399961+0530 FirebaseTest[60749:4515213] FirebasePlugin[native]: Enter background: FCM direct channel = false
```

**Comment by dpa99c** [comment] 2020-08-05 15:57
The plugin will only return values in the `user` object in the `getCurrentUser()` callback which are not empty in the current Firebase user account.

In the case of user's name, this is not being returned because it is returning a `nil` value from the Firebase iOS SDK:

![Screenshot 2020-08-05 at 16 36 04](https://user-images.githubusercontent.com/2345062/89435310-9b325c80-d73c-11ea-8eb9-34e0e3171098.png)

According to [this open issue against the Firebase iOS SDK](https://github.com/firebase/firebase-ios-sdk/issues/4393#issuecomment-559012512), this is expected behaviour because the Apple ID token doesn't contain the user's name.

Therefore rather than being a bug with this plugin, this is a current limitation of the Firebase SDK which may or may not be resolved in a future version.

There is a [suggested workaround](https://github.com/firebase/firebase-ios-sdk/issues/4393#issuecomment-616357186) in the same issue which involves implementing the `didCompleteWithAuthorization` delegate method to extract the user's full name and update the user's Firebase account profile with it.
However this adds considerable complexity to the plugin and involves writing data back to the user's Firebase account profile because the Firebase SDK currently doesn't do this itself, so I consider this to be a low-priority enhancement as opposed to plugin bug.

**Comment by chaitanya-deep** [comment] 2020-08-05 16:19
Understood. Thank you for the quick response.
My bad. I should've searched the firebase sdk for similar issues. I think this issue can be closed.

**Comment by dpa99c** [comment] 2020-08-05 16:22
@chaitanya-deep There's still the possibility of adding the workaround to this plugin as an enhancement if other plugin users think this is worthwhile. 
So I'll leave this open as a possible future enhancement until either the Firebase SDK fixes it or we implement the workaround.

**Comment by ishaiavrahami** [comment] 2021-06-22 20:43
Hello, i saw a new version was released 6 days ago and full name or name is still not implemented. Is there any updates?

**Comment by tzappia** [comment] 2021-09-27 14:41
I have a fork with a few changes that I will split up into separate PRs after doing lots more testing, but what I have done is return the first and last name provided by Apple during sign up only. It doesn't attempt to write this to the Firebase displayName property but makes it available to your app to do so.
https://github.com/tzappia/cordova-plugin-firebasex/tree/auth-emulator-and-apple-info

**Closed** 2022-01-28 17:04 UTC
Labels: feature request, runtime issue, ios, Firebase SDK, caveat, wontfix
