### ISSUE TITLE
iOS 17/Xcode 15 build issues

### ISSUE THREAD

**Issue by ThiloGHL** [dpa99c/cordova-plugin-firebasex#830] opened 2023-09-11 09:46 UTC
Has anyone tried building an app with this plugin for iOS 17 yet?

It seems that the plugin needs to be updated for iOS17. There are following problems within the Firebase Pods folder:

1. In the xcconfig files, 'DT_TOOLCHAIN_DIR' needs to be replaced with 'TOOLCHAIN_DIR'
2. I'm getting following error for the file 'Pods/FirebaseFirestore/Firestore/Source/API/FIRFirestoreSettings.mm' line 33: An attribute list cannot appear here
It can be fixed by replacing
`ABSL_CONST_INIT extern "C" const int64_t kFIRFirestoreCacheSizeUnlimited =  Settings::CacheSizeUnlimited;`
with
`const int64_t kFIRFirestoreCacheSizeUnlimited =  Settings::CacheSizeUnlimited;`
(But I do not know if this can result in any problems)

With the corresponding fixes, I'm able to build the app and push notifications are working.

**Comment by Samir-Lora** [comment] 2023-09-14 13:57
I have the same issue

**Comment by yusufcaglar** [comment] 2023-09-17 10:40
I have the same issue as well. @peterfriese

**Comment by xiesw** [comment] 2023-09-19 02:47
same issue

**Comment by jay-benzatine** [comment] 2023-09-19 09:47
Hello,

I have the same issue whenever I run my existing app after updating Xcode 15.0.

![image](https://github.com/dpa99c/cordova-plugin-firebasex/assets/77785939/07b0ffd0-42e6-4b7b-b5d6-860f9c97ab60)

Please give solution as soon as possible.

**Comment by dpa99c** [comment] 2023-09-19 09:55
The issue isn't that this plugin doesn't support Xcode 15 / iOS 17, it's that the [default pinned version (v10.10.0)](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L153) of the Firebase SDK for iOS does not.

Try specifying the [latest version (v10.15.0) of the Firebase SDK for iOS](https://firebase.google.com/support/release-notes/ios#version_10150_-_sept_12_2023) when installing the plugin into your project:

```
cordova plugin rm cordova plugin add cordova-plugin-firebasex 
cordova plugin add cordova-plugin-firebasex --variable IOS_FIREBASE_SDK_VERSION=10.15.0
```

**Comment by jay-benzatine** [comment] 2023-09-19 10:08
@dpa99c I am running the Flutter app this issue is occurring?

Do you have any idea?

**Comment by yusufcaglar** [comment] 2023-09-19 14:21
> Hello,
> 
> I have the same issue whenever I run my existing app after updating Xcode 15.0.
> 
> ![image](https://user-images.githubusercontent.com/77785939/268913294-07b0ffd0-42e6-4b7b-b5d6-860f9c97ab60.png)
> 
> Please give solution as soon as possible.

I solved this issue on Xcode by using dpa99c's solution. Go to Project > Project Dependencies > Change Firebase to 10.0.15. Screenshot below.  
![Solution](https://github.com/dpa99c/cordova-plugin-firebasex/assets/32461567/0936fe53-4620-4212-a9e1-7001cd595506)

**Comment by yusufcaglar** [comment] 2023-09-19 14:22
> The issue isn't that this plugin doesn't support Xcode 15 / iOS 17, it's that the [default pinned version (v10.10.0)](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L153) of the Firebase SDK for iOS does not.
> 
> Try specifying the [latest version (v10.15.0) of the Firebase SDK for iOS](https://firebase.google.com/support/release-notes/ios#version_10150_-_sept_12_2023) when installing the plugin into your project:
> 
> ```
> cordova plugin rm cordova-plugin-firebasex 
> cordova plugin add cordova-plugin-firebasex --variable IOS_FIREBASE_SDK_VERSION=10.15.0
> ```
> 
> If you get build errors with this, make sure your [local Cocoapods repo is up-to-date](https://github.com/dpa99c/cordova-plugin-firebasex#out-of-date-pods)

Thanks man.

**Comment by peterdsp** [comment] 2023-09-20 08:47
I have the same issue

**Comment by romamaslennikov** [comment] 2023-09-20 08:50
and i have the same issue

**Comment by dpa99c** [comment] 2023-09-20 08:56
Please use [the solution](https://github.com/dpa99c/cordova-plugin-firebasex/issues/830#issuecomment-1725189302) above to resolve this issue with the Firebase SDK for iOS.

**Comment by peterdsp** [comment] 2023-09-20 09:06
> Please use [the solution](https://github.com/dpa99c/cordova-plugin-firebasex/issues/830#issuecomment-1725189302) above to resolve this issue with the Firebase SDK for iOS.

![image](https://github.com/dpa99c/cordova-plugin-firebasex/assets/45949870/4b6628c8-f2ce-4c84-b5b1-9d85c60df57f)

**Comment by dpa99c** [comment] 2023-09-20 09:12
@peterdsp you removed and re-added the plugin with the new SDK version specified?

If that doesn't resolve it, also remove and re-add the iOS platform project:

`cordova platform rm ios --nosave && cordova platform add ios --nosave`

**Comment by peterdsp** [comment] 2023-09-20 09:19
> cordova platform rm ios --nosave && cordova platform add ios --nosave

yes and i get this now when pod install
[!] CocoaPods could not find compatible versions for pod "Firebase/Firestore":
  In Podfile:
    Firebase/Firestore (= 15.0.15)

**Comment by peterdsp** [comment] 2023-09-20 09:23
**pod install**
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Firebase/Firestore":
  In Podfile:
    Firebase/Firestore (= 10.0.15)

**Comment by dpa99c** [comment] 2023-09-20 09:24
@peterdsp did you run `pod repo update` (as instructed above) to update your local Cocoapods repo with the latest pod versions?

**Comment by peterdsp** [comment] 2023-09-20 09:27
but it keeps not running with the same error

**Comment by peterdsp** [comment] 2023-09-20 09:29
Build is not failing only if I change in **FIRFirestoneSettings.mm** 
**ABSL_CONST_INIT extern "C" const int64_t kFIRFirestoreCacheSizeUnlimited =
    Settings::CacheSizeUnlimited;**
    to
    **extern "C" const int64_t kFIRFirestoreCacheSizeUnlimited =
    Settings::CacheSizeUnlimited;**

**Comment by jay-benzatine** [comment] 2023-09-20 09:30
@dpa99c @peterdsp 

Yes `pod repo update` is working but first, if anyone is using Flutter please update the Firebase library in the pubspec.yml file first then it works.

**Comment by dpa99c** [comment] 2023-09-20 09:31
If using Cordova, make sure you're use the latest Cordova iOS platform version:

`cordova platform rm ios && cordova platform add ios@latest`

**Comment by peterdsp** [comment] 2023-09-20 09:32
I dont use flutter is a native swift project

**Comment by jay-benzatine** [comment] 2023-09-20 09:33
> I dont use flutter is a native swift project

So you have to install the latest copapods using this, 

`cordova platform rm ios && cordova platform add ios@latest`

**Comment by peterdsp** [comment] 2023-09-20 09:34
> cordova platform rm ios && cordova platform add ios@latest

I get this: Current working directory is not a Cordova-based project.

**Comment by dpa99c** [comment] 2023-09-20 09:36
@peterdsp Is it a Cordova project? 
Did you use the Cordova CLI to create the Xcode project?

**Comment by jay-benzatine** [comment] 2023-09-20 09:37
@peterdsp 
Here are the latest release versions of Firebase.
Link:- https://firebase.google.com/support/release-notes/ios 

You have to update your Fireastore version to `"Version 10.15.0"`.

**Comment by jay-benzatine** [comment] 2023-09-20 09:43
@peterdsp 

This issue has been solved in the official Firebase-IOS-SDK.

Here is the link,
https://github.com/firebase/firebase-ios-sdk/issues/11408

**Comment by peterdsp** [comment] 2023-09-20 10:48
Found the solution!
add on podfile 

pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.15.0'

**Comment by rasidre** [comment] 2023-09-21 07:39
any updates on that? using react-native

**Comment by Nazar2** [comment] 2023-09-21 09:11
same issue

**Comment by dpa99c** [comment] 2023-09-21 09:12
Locking this issue now as the solution above is clear

**Comment by dpa99c** [comment] 2023-12-20 10:20
Closing as resolved

**Closed by dpa99c** 2023-12-20 10:20 UTC
