### ISSUE TITLE
Notification image support on ios

### ISSUE THREAD

**Issue by shikhar-0017** [dpa99c/cordova-plugin-firebasex#795] opened 2023-02-20 10:55 UTC
Any idea when this plugin will start supporting notification images for iOS??
Or is there any way we can implement this by using this plugin??

**Comment by halie412** [comment] 2023-03-30 03:27
hi @shikhar-0017 

Do you find any solution?

**Comment by shikhar-0017** [comment] 2023-03-30 07:38
No, this plugin does not have support for notification image

**Comment by dpa99c** [comment] 2023-03-30 07:57
Notification images for iOS is not feasible to implement in the context of this plugin - [see here](https://github.com/dpa99c/cordova-plugin-firebasex/issues/138#issuecomment-529476540)

(Closing as duplicate of https://github.com/dpa99c/cordova-plugin-firebasex/issues/138)

**Closed by dpa99c** 2023-03-30 07:57 UTC

**Comment by ollm** [comment] 2023-04-06 09:10
If you want to show images in iOS notifications, I have added a tutorial with the necessary steps to do it: https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/docs/IOS_NOTIFICATION_SERVICE.md

For now, until the new version of `cordova-ios` comes out, you will have to install `corodva-ios` from the source code, since the `v6.2.0` does not have the changes implemented to support multiple provisioning profiles.

``` bash
cordova platform add https://github.com/apache/cordova-ios.git
```

I have that working correctly in my app for a couple of years.

**Comment by dpa99c** [comment] 2023-04-06 10:58
@ollm Thanks for documenting this - it's really useful

**Comment by GustavoFMorales** [comment] 2023-05-29 19:03
Hey guys,

Can you tell me if there is any automatic way to perform this process (https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/docs/IOS_NOTIFICATION_SERVICE.md ) using Cordova-ios 6.3.0?
