### ISSUE TITLE
Android Build failed: Dependency failing

### ISSUE THREAD

**Issue by HansKrywaa** [dpa99c/cordova-plugin-firebasex#466] opened 2020-07-21 07:17 UTC
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [ ] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [ ] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

When trying to switch from `9.1.1` to `10.1.2` i get the following build error in android:
```
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[19.0.
  0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
  
  Dependency failing: com.google.firebase:firebase-messaging:19.0.0 -> com.google.firebase:firebase-iid@[19.0.0], but fire
  base-iid version was 20.1.5.
  
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.firebase:firebase-crashlytics@17.0.1
  -- Project 'app' depends onto com.google.firebase:firebase-analytics@17.2.1
  -- Project 'app' depends onto com.google.android.gms:play-services-tagmanager-api@17.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-crashlytics-ndk@17.0.1
  -- Project 'app' depends onto com.google.firebase:firebase-perf@18.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-tagmanager@17.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-messaging@19.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-inappmessaging-display@19.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-api@17.2.1
  -- Project 'app' depends onto com.google.firebase:firebase-config@18.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-iid@20.1.5
  -- Project 'app' depends onto com.google.firebase:firebase-inappmessaging@19.0.0
```

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `android 8.1.0; ios 5.1.1`
- Dev machine OS and version, e.g.
    - OSX
        - `ProductName: Mac OS X - ProductVersion: 10.15.6 - BuildVersion: 19G73`	
	
_Android build issue:_	
- Node JS version
    - `v12.16.1`
- Gradle version
	- `4.10.3			buildOutputCleanup
5.6.1			vcs-1`

**Comment by dpa99c** [comment] 2020-07-21 15:21
As you can [see from the `plugin.xml`](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L77), this plugin does not include the `com.google.firebase:firebase-iid` SDK component so it's likely this is being pulled in by another plugin in your project and is conflicting with the Firebase SDK components this plugin references.

You can confirm the plugin builds correctly in isolation by building the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) and see [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex#specifying-android-library-versions) for how you can specify Firebase SDK component versions when installing this plugin to resolve version conflicts with other plugins which include Firebase SDK components.

**Comment by HansKrywaa** [comment] 2020-07-21 15:30
What i don't understand is, if i search my `plugins` Folder for **com.google.firebase:firebase-iid** i can't find any appearances. Also downgrading back to `9.1.1` works

**Comment by dpa99c** [comment] 2020-07-21 15:40
> What i don't understand is, if i search my `plugins` Folder for **com.google.firebase:firebase-iid** i can't find any appearances.

Try removing & re-adding the Android platform in case it's legacy entry:

    cordova platform rm android --nosave && cordova platform add android --nosave

> downgrading back to `9.1.1` works

The [default Android SDK component versions ](https://github.com/dpa99c/cordova-plugin-firebasex/commit/2450fd18a4fac5a04c116d7d49ec52804fee24bf) have been bumped to the latest releases since so it's likely the older version of `firebase-messaging` works with the pinned version of `firebase-iid` but the newer version does not.
You can manually specify the version of each Android SDK component referenced by this plugin as outlined in the documentation.

**Comment by HansKrywaa** [comment] 2020-07-24 08:49
I removed the Platform and build again, still can't find any `firebase-iid` references.

I currently specify manual the version. This is my "config":

```
        "FIREBASE_ANALYTICS_COLLECTION_ENABLED": "false",
        "FIREBASE_PERFORMANCE_COLLECTION_ENABLED": "false",
        "FIREBASE_CRASHLYTICS_COLLECTION_ENABLED": "false",
        "ANDROID_ICON_ACCENT": "#5A71A7",
        "ANDROID_PLAY_SERVICES_TAGMANAGER_VERSION": "17.0.0",
        "ANDROID_FIREBASE_CORE_VERSION": "17.0.0",
        "ANDROID_FIREBASE_MESSAGING_VERSION": "19.0.0",
        "ANDROID_FIREBASE_CONFIG_VERSION": "18.0.0",
        "ANDROID_FIREBASE_PERF_VERSION": "18.0.0",
        "ANDROID_FIREBASE_AUTH_VERSION": "18.0.0",
        "ANDROID_CRASHLYTICS_VERSION": "2.10.1",
        "ANDROID_CRASHLYTICS_NDK_VERSION": "2.1.0",
        "ANDROID_SHORTCUTBADGER_VERSION": "1.1.22",
        "ANDROID_FIREBASE_ANALYTICS_VERSION": "17.2.1",
        "ANDROID_PLAY_SERVICES_AUTH_VERSION": "17.0.0",
        "ANDROID_FIREBASE_INAPPMESSAGING_VERSION": "19.0.0",
        "ANDROID_FIREBASE_FIRESTORE_VERSION": "21.4.0",
        "ANDROID_GSON_VERSION": "2.8.6",
        "ANDROID_FIREBASE_CRASHLYTICS_VERSION": "17.0.1",
        "ANDROID_FIREBASE_CRASHLYTICS_NDK_VERSION": "17.0.1"
```

```
  Dependency failing: com.google.firebase:firebase-messaging:19.0.0 -> com.google.firebase:firebase-iid@[19.0.0], but fire
  base-iid version was 20.1.5.
```
I don't know how to get to know where this firebase-iid comes from

**Comment by dpa99c** [comment] 2020-07-24 11:29
Can you try building the example project to validate your build environment?
If that works OK, then the issue is fairly certain to be specific to your project.

**Comment by HansKrywaa** [comment] 2020-07-24 17:47
I just tried the example project with my Config i mentioned above. It fails with the same Reason:

```
BUILD FAILED in 1s
/Users/hanskrywalsky/IdeaProjects/cordova/cordova-plugin-firebasex-test/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[19.0.
  0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
  
  Dependency failing: com.google.firebase:firebase-messaging:19.0.0 -> com.google.firebase:firebase-iid@[19.0.0], but fire
  base-iid version was 20.1.5.
  
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.firebase:firebase-crashlytics@17.0.1
  -- Project 'app' depends onto com.google.firebase:firebase-analytics@17.2.1
  -- Project 'app' depends onto com.google.android.gms:play-services-tagmanager-api@17.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-crashlytics-ndk@17.0.1
  -- Project 'app' depends onto com.google.firebase:firebase-perf@18.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-tagmanager@17.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-messaging@19.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-inappmessaging-display@19.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-api@17.2.1
  -- Project 'app' depends onto com.google.firebase:firebase-config@18.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-iid@20.1.5
  -- Project 'app' depends onto com.google.firebase:firebase-inappmessaging@19.0.0
  
  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

```

**Comment by dpa99c** [comment] 2020-07-25 07:37
> I just tried the example project with my Config i mentioned above

Please try it without your config -  I believe that's the possible cause due to conflicting versions.
Try building the example project with the plugin defaults.

**Comment by HansKrywaa** [comment] 2020-07-25 07:44
The example Project builds successfully if i don't use my config in there. But my Config worked so far and also still works in `9.1.1` 🤔

**Comment by dpa99c** [comment] 2020-07-25 08:08
The problem is therefore your config. TL;DR: use the default config unless you have good reason not to.
Closing as the plugin works fine with default config so this issue is specific to your custom config and won't affect other users.

**Closed by dpa99c** 2020-07-25 08:08 UTC
Labels: android, build issue, plugin conflict, support

**Comment by capc0** [comment] 2020-08-28 08:20
FYI I also had problems with conflicting versions since I updated to version 10.2.0. I ended up removing all pinned versions and used the default versions from the example project.

```
                 "ANDROID_PLAY_SERVICES_TAGMANAGER_VERSION": "17.0.0",
                "ANDROID_PLAY_SERVICES_AUTH_VERSION": "18.0.0",
                "ANDROID_FIREBASE_ANALYTICS_VERSION": "17.4.3",
                "ANDROID_FIREBASE_MESSAGING_VERSION": "20.2.1",
                "ANDROID_FIREBASE_CONFIG_VERSION": "19.1.4",
                "ANDROID_FIREBASE_PERF_VERSION": "19.0.7",
                "ANDROID_FIREBASE_AUTH_VERSION": "19.3.1",
                "ANDROID_FIREBASE_FIRESTORE_VERSION": "21.4.3",
                "ANDROID_FIREBASE_CRASHLYTICS_VERSION": "17.0.1",
                "ANDROID_FIREBASE_CRASHLYTICS_NDK_VERSION": "17.0.1",
                "ANDROID_GSON_VERSION": "2.8.6"
```

Then I ran into another conflicting issue 

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preReleaseBuild'.
> Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
   > Could not resolve com.squareup.okio:okio:1.13.0.
     Required by:
         project :app
      > Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints:
           Dependency path 'android:app:unspecified' --> 'com.squareup.okhttp3:okhttp:3.12.1' --> 'com.squareup.okio:okio:1.15.0'
           Dependency path 'android:app:unspecified' --> 'com.google.firebase:firebase-perf:19.0.7' --> 'com.squareup.okhttp3:okhttp:3.12.1' --> 'com.squareup.okio:okio:1.15.0'
           Dependency path 'android:app:unspecified' --> 'com.google.firebase:firebase-firestore:21.4.3' --> 'com.squareup.okhttp:okhttp:2.7.5' --> 'com.squareup.okio:okio:1.6.0'
           Dependency path 'android:app:unspecified' --> 'com.google.firebase:firebase-firestore:21.4.3' --> 'io.grpc:grpc-okhttp:1.21.0' --> 'com.squareup.okio:okio:1.13.0'
           Constraint path 'android:app:unspecified' --> 'com.squareup.okio:okio' strictly '1.13.0' because of the following reason: releaseRuntimeClasspath uses version 1.13.0
           Constraint path 'android:app:unspecified' --> 'com.squareup.okio:okio' strictly '1.13.0' because of the following reason: releaseRuntimeClasspath uses version 1.13.0
           Constraint path 'android:app:unspecified' --> 'com.squareup.okio:okio' strictly '1.13.0' because of the following reason: releaseRuntimeClasspath uses version 1.13.0
```

this was due to the specified OKHTTP_VERSION from the ```uk.co.workingedge.phonegap.plugin.launchnavigator``` plugin. I changed the pinned version from 3.12.0 to 3.12.1 and the build works again.

@dpa99c I dont know if you maybe want to update the default version of your launchnavigator plugin. Not sure if other builds would break.

**Comment by rolinger** [comment] 2021-03-15 16:47
@dpa99c @capc0 @EinfachHans - I don't know what happened or changed but I did nothing.  Yesterday it compiled 20+ times as I was testing new JS code and today it suddenly produces the below errors:

```
> ionic-v1.cmd build
[12:29:58] Invoking sass gulp task.
> cordova.cmd build android
cordova-custom-config: Skipping auto-restore of config file backup(s)
Conflict found, edit-config changes from config.xml will overwrite plugin.xml changes
Running command: node C:\Users\RPO\dev\Eventis_0.3.1\hooks\after_prepare\010_add_platform_class.js C:\Users\RPO\dev\Eventis_0.3.1
cordova-custom-config: Applied custom config from config.xml to C:\Users\RPO\dev\Eventis_0.3.1\platforms\android\app\src\main\AndroidManifest.xml
cordova-plugin-androidx-adapter: Processed 81 source files in 1927ms
cordova-plugin-firebasex: Preparing Firebase on Android
cordova-plugin-firebasex: Updated colors.xml with accent color
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=c:\users\rpo\appdata\local\android\sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.firebase:firebase-iid:[20.2.1].
     Required by:
         project :app > com.google.firebase:firebase-messaging:20.2.1
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/firebase/firebase-iid/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/firebase/firebase-iid/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/firebase/firebase-iid/maven-metadata.xml'.
                  > Read timed out
```

I haven't changed any platform or plugins in weeks.  But yet it says `edit-config changes from config.xml will overwrite plugin.xml changes".  I have no idea where that is coming from or if its related to the new error that came out of nowhere.

Its as if some dependency downloaded on the fly has changed.

Here is my plugins list:
```
com.peerio.cordova.plugin.carrier 1.0.1 "Carrier"
com.phonegap.plugins.nativesettingsopener 1.0.1 "Native settings"
cordova-clipboard 1.3.0 "Clipboard"
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-instagram-plugin 0.6.0 "Instagram"
cordova-launch-review 4.0.1 "Launch Review"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-appinfo 2.1.2 "AppInfo Plugin"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-customurlscheme 5.0.2 "Custom URL scheme"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-device-motion 2.0.1 "Device Motion"
cordova-plugin-device-orientation 2.0.1 "Device Orientation"
cordova-plugin-deviceinformation 2.0.2 "DeviceInformation"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-email 1.2.7 "EmailComposer"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-facebook4 6.4.0 "Facebook Connect"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-downloader 0.4.0 "Downloader"
cordova-plugin-file-md5 0.3.3 "MD5 Checksum"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebasex 10.1.2-cli "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-qrscanner 3.0.1 "QRScanner"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-screensize 1.3.1 "screensize"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sms-plugin 1.0.0 "Cordova SMS Plugin"
cordova.plugins.diagnostic 6.0.2 "Diagnostic"
twitter-connect-plugin 0.6.0 "Twitter Connect"
```

**Comment by rolinger** [comment] 2021-03-15 18:32
I resolved my issue by finally doing the scary move to firebasex@11.0.3 - I was pinned for a while to the firebasex-cli@10.1.2 version and can't recall why....but this leap of faith worked (this time).
