### ISSUE TITLE
Build failed for IOS

### ISSUE THREAD

**Issue by roushankumar01** [dpa99c/cordova-plugin-firebasex#254] opened 2019-12-12 08:41 UTC
# Bug report

Getting error while building for IOS

** BUILD FAILED **

The following build commands failed:
        CompileC /var/root/Library/Developer/Xcode/DerivedData/WB_Single_Mobile_Platform-gqxvrylocwftvcgwehlcnqzajehj/Build/Intermediates.noindex/WB\ Single\ Mobile\ Platform.build/Debug-iphonesimulator/WB\ Single\ Mobile\ Platform.build/Objects-normal/x86_64/FirebasePlugin.o /Users/sunit.bhattacharya/Documents/Projects/SMP/Single_Mobile_Platform/platforms/ios/WB\ Single\ Mobile\ Platform/Plugins/cordova-plugin-firebasex/FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Command finished with error code 65: xcodebuild -workspace,WB Single Mobile Platform.xcworkspace,-scheme,WB Single Mobile Platform,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 11 Pro Max,build,CONFIGURATION_BUILD_DIR=/Users/sunit.bhattacharya/Documents/Projects/SMP/Single_Mobile_Platform/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/sunit.bhattacharya/Documents/Projects/SMP/Single_Mobile_Platform/platforms/ios/build/sharedpch
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/sunit.bhattacharya/Documents/Projects/SMP/Single_Mobile_Platform/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[ERROR] An error occurred while running subprocess cordova.

**Screenshots**
<img width="1452" alt="Screenshot 2019-12-12 at 1 00 29 PM" src="https://user-images.githubusercontent.com/19370055/70691707-bcdb6100-1cdf-11ea-9071-9b8bf89a79d5.png">

When i am trying to build from Xcode by opening WB Single Mobile Platform.xcworkspace i am getting error 
**'Firebase.h' file not found**
<img width="1156" alt="Screenshot 2019-12-12 at 1 07 31 PM" src="https://user-images.githubusercontent.com/19370055/70691978-691d4780-1ce0-11ea-885f-1890649c36af.png">

**Environment information**

- Cordova CLI version 
	- 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	-  Installed platforms:
         android 8.1.0
         browser 6.0.0
         ios 5.1.1
         Available platforms: 
         electron ^1.0.0
         osx ^5.0.0
         windows ^7.0.0
- Plugins & versions installed in project (including this plugin)
    - call-number 0.0.2 "Cordova Call Number Plugin"
com-badrit-base64 0.2.0 "Base64"
com-sarriaroman-photoviewer 1.2.4 "PhotoViewer"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-android-rootbeer 1.0.0 "RootBeer Library for Cordova"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-document-viewer 0.9.13 "SitewaertsDocumentViewer"
cordova-plugin-email-composer 0.9.2 "EmailComposer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-opener2 2.2.1 "File Opener2"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.5.6 "cordova-plugin-filepath"
cordova-plugin-filepicker 1.1.6 "File Picker"
cordova-plugin-fingerprint-aio 3.0.0 "FingerprintAllInOne"
cordova-plugin-firebasex 7.0.1 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-sms-receive 1.0.2 "SMS Receive"
cordova-plugin-speechrecognition 1.1.2 "Speech Recognition"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-telerik-imagepicker 2.3.3 "ImagePicker"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 3.4.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
integrator-cordova-plugin-downloader 0.0.1 "Downloader"`

- Dev machine OS and version, e.g.
    - OSX
        ProductName:    Mac OS X
       ProductVersion: 10.15.1
       BuildVersion:   19B88
        
_iOS build issue:_
- Node JS version
    - v12.13.0
- XCode version
 - 11.2.1

This issue is already closed but that is solution is not working,
Please help

**Comment by dpa99c** [comment] 2019-12-12 09:22
This error means the Firebase SDK was not included into your build.
The most frequent cause is out-of-date or incorrectly configured Cocoapods repo.

Please build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to validate your dev environment and rule out the cause being within your own project.

**Comment by roushankumar01** [comment] 2019-12-12 10:08
I have already tried to build [https://github.com/dpa99c/cordova-plugin-firebasex-test](url)(example project) also, but getting same error. @dpa99c please help.

**Comment by dpa99c** [comment] 2019-12-12 10:45
If the example project fails, then your dev environment seems to be the cause.
Ensure Cocoapods is installed and the repo is up-to-date: `cd platforms/ios && pod repo update && pod install`

**Comment by roushankumar01** [comment] 2019-12-12 13:34
After executing above cmd **(cd platforms/ios && pod repo update && pod install)** reported issue solved by now i am getting this error

**BUILD FAILED**
PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /var/root/Library/Developer/Xcode/DerivedData/WB_Single_Mobile_Platform-evvceygsloufvwalfrqhpkjwryxr/Build/Intermediates.noindex/WB\ Single\ Mobile\ Platform.build/Debug-iphonesimulator/WB\ Single\ Mobile\ Platform.build/Script-73C98B7DEF781D2067DC0672.sh (in target 'WB Single Mobile Platform' from project 'WB Single Mobile Platform')
    cd /Users/sunit.bhattacharya/Documents/Projects/Archive/platforms/ios
    /bin/sh -c /var/root/Library/Developer/Xcode/DerivedData/WB_Single_Mobile_Platform-evvceygsloufvwalfrqhpkjwryxr/Build/Intermediates.noindex/WB\\\ Single\\\ Mobile\\\ Platform.build/Debug-iphonesimulator/WB\\\ Single\\\ Mobile\\\ Platform.build/Script-73C98B7DEF781D2067DC0672.sh
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

** BUILD FAILED **


The following build commands failed:
        PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /var/root/Library/Developer/Xcode/DerivedData/WB_Single_Mobile_Platform-evvceygsloufvwalfrqhpkjwryxr/Build/Intermediates.noindex/WB\ Single\ Mobile\ Platform.build/Debug-iphonesimulator/WB\ Single\ Mobile\ Platform.build/Script-73C98B7DEF781D2067DC0672.sh
(1 failure)
Command finished with error code 65: xcodebuild -workspace,WB Single Mobile Platform.xcworkspace,-scheme,WB Single Mobile Platform,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 11 Pro Max,build,CONFIGURATION_BUILD_DIR=/Users/sunit.bhattacharya/Documents/Projects/Archive/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/sunit.bhattacharya/Documents/Projects/Archive/platforms/ios/build/sharedpch
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/sunit.bhattacharya/Documents/Projects/Archive/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[ERROR] An error occurred while running subprocess cordova.

**Screenshoot**
<img width="1624" alt="Screenshot 2019-12-12 at 7 02 27 PM" src="https://user-images.githubusercontent.com/19370055/70716235-fa58e200-1d11-11ea-83bb-aa25ca594e81.png">

@dpa99c please help in solving this problem also.

**Comment by dpa99c** [comment] 2019-12-12 14:55
See the error message:
> error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Closing as these issues are with your build environment not the plugin code.

**Closed by dpa99c** 2019-12-12 14:55 UTC
Labels: build issue, ios, support

**Comment by ZumelzuR** [comment] 2020-12-16 14:43
I have the same problem when I'm building for ios with "prod" tag.

I have:

 - MacOS catalina 10.5.4 
* Xcode version 12.2
* cordova-ios 6.0.0

For me the solution that worked was first sign the app on xcode after the first build issue (open platform/ios with xcode and sign the app). Then I build with the commands that people suggest here, but I have to add the "--device" tag also. After that work good :)

    ionic cordova run ios --prod --release --buildFlag="-UseModernBuildSystem=0"  --device
